### ISSUE TITLE
Generating Zerodha Access Tokens

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1042]
#### Expected Behavior

[Account Types](https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/zerodha#02-Account-Types) is simple. Instead of 
> 3. Make a POST request to /session/token with the request_token and checksum (SHA-256 of api_key + request_token + api_secret) and obtain the access_token.

, it links to a script in https://github.com/QuantConnect/lean.brokerages.zerodha that generates your `access_token`.

Sample script:
```
from kiteconnect import KiteConnect
​
kite = KiteConnect(api_key=api_key_here)
​
# Redirect the user to the login url obtained
# from kite.login_url(), and receive the request_token
# from the registered redirect url after the login flow.
# Once you have the request_token, obtain the access_token
# as follows.
​
request_token = input ("Enter request_token_here:")
data = kite.generate_session(request_token, api_secret=api_secret_here)
kite.set_access_token(data["access_token"])
print(f"your access_token is \n{data['access_token']}")
```

#### Actual Behavior

This script is not made, so we don't currently link to it. Waiting on a Zerodha API key before we can test the script.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
ty @rjra2611 


To use the script you will need to get your request token:

- Fill your Zerodha API Key in this link: http://kite.trade/connect/login?api_key=<your_api_key>
- Open the link in your browser which will redirect you to Kite login page.
- Your request token will the the value of key reuest_token in the success URL.

**Comment by rjra2611** [comment]
Ty @DerekMelchin 

I have updated the script so that users won't need to use `http://kite.trade/connect/login?api_key=<your_api_key>` and this link will directly open in their browser so that they can log in and fetch their request token 

```
from kiteconnect import KiteConnect
import webbrowser

kite = KiteConnect(api_key=api_key_here)
​webbrowser.open(kite.login_url())
request_token = input ("Enter request_token_here:")
data = kite.generate_session(request_token, api_secret=api_secret_here)
kite.set_access_token(data["access_token"])
print(f"your access_token is \n{data['access_token']}")
```
