### ISSUE TITLE
Missing links to backtest/optimization results

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1046]
#### Expected Behavior

- [View All Backtests](https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/getting-started#03-View-All-Backtests) and [View All Optimizations](https://www.quantconnect.com/docs/v2/cloud-platform/optimization/getting-started#04-View-All-Optimizations) link to https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results and https://www.quantconnect.com/docs/v2/cloud-platform/optimization/results
-- > "If there is a play icon to the left of the name, it's a backtest result. If there is a fast-forward icon next to the name, it's an optimization result."
- [View Individual Backtest Results](https://www.quantconnect.com/docs/v2/cloud-platform/optimization/getting-started#03-View-Individual-Backtest-Results) links to https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results
-- > "backtest result page"

#### Actual Behavior

Links are missing

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closed by https://github.com/QuantConnect/Documentation/pull/1052
