### ISSUE TITLE
Clarification date order custom data

### ISSUE THREAD

**Issue by gustavarcticmill** [QuantConnect/Documentation#106]
I had some problems importing my custom data using a CSV and SubscriptionTransportMedium.RemoteFile. I finally got it working by making sure the rows in the csv file was in chronological date order. I did not find anything in the docs stating this. Is this the case or did I misunderstand something?

**Comment by DerekMelchin** [comment]
Added in docs v2 [here](https://www.quantconnect.com/docs/v2/research-environment/tutorials/requesting-historical-data/custom-data#03-Define-Custom-Data).
