### ISSUE TITLE
Indicator Reference code generator is outdated

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Documentation#1091]
#### Actual Behavior
Indicator Reference code generator is not updated to fetch the correct reference from `Resources\qcalgorithm-api` after Writing Algorithm API reference code generator refactoring.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
The `Indicator-Reference-Code-Generator` needs to save the constructor methods to `Resources\indicators\constructors` with the same format of `Resources\qcalgorithm-api` (e.g.: [bb.html](https://github.com/QuantConnect/Documentation/blob/master/Resources/qcalgorithm-api/bb.html)). It will have this content for `Resources\indicators\constructors\bollinger_bands.html`: [Create Manual Indicators.html#L86:L181](https://github.com/QuantConnect/Documentation/blob/master/03%20Writing%20Algorithms/28%20Indicators/01%20Supported%20Indicators/18%20Bollinger%20Bands/02%20Create%20Manual%20Indicators.html#L86:L181). We should use PHP to fetch the resources. Please note that the method container can be fetched from [ _method_container.html](https://github.com/QuantConnect/Documentation/blob/master/Resources/qcalgorithm-api/_method_container.html) and we should save the `MovingAverageType` HTML in a dedicated file and import it as well.
