### ISSUE TITLE
Some TransactionManager methods aren't documented

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1125]
#### Expected Behavior

The [Transaction Manager docs](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-management/transaction-manager) cover `GetOrdersByBrokerageId`, `GetOrders`, and `OrdersCount`.
`OrdersCount` is useful because if OrdersCount is zero, we know we don't need to iterate the collection.

#### Actual Behavior

These methods aren't documented.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/db8c7501df06d1c2ccde750db5ba41dcb7e8d89f
