### ISSUE TITLE
Update API Yaml to Include Reading Insights

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1141]
#### Expected Behavior
Docs and YAML include Reading Live Insights

#### Actual Behavior
No documentation on reading live insights.

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/808853fb581b052e663878f0fe7b6d31dce63028.
