### ISSUE TITLE
Update M1 Install Process for Local Platform

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1142]
#### Actual Behavior
Current install process tells user to do extra work that is not required - and ends up corrupting the docker installation!
Reduce to the minimum - GUI guided installation steps, https://docs.docker.com/desktop/install/mac-install/
Delete the "extra" you have to do for M1

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Was this issue already resolved by these commits?
- https://github.com/QuantConnect/Documentation/commit/ab0efe6b312004f5d173a02ac6f2c9c94a40e65e
- https://github.com/QuantConnect/Documentation/commit/28d826adc7b22dd4afb08b28b4ea7225f70d37e0
