### ISSUE TITLE
Create Null Buying Power Model Docs

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1150]
#### Expected Behavior
New Null buying power models documented 
https://github.com/QuantConnect/Lean/pull/6977

#### Checklist
- [x] I have filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/9c93da9615f93c0f26b3d4f6b379c92c2436ade7
