### ISSUE TITLE
Font Bundle for LEAN Foundation

### ISSUE THREAD

**Issue by oussamanahdi** [QuantConnect/Documentation#1156]
List of Fonts: 

Open Sans: https://fonts.google.com/specimen/Open+Sans
Rubik: https://fonts.google.com/specimen/Rubik
Roboto: https://fonts.google.com/specimen/Roboto
Lato: https://fonts.google.com/specimen/Lato
Oswald: https://fonts.google.com/specimen/Oswald
PlayFair: https://fonts.google.com/specimen/Playfair+Display
Josefin Sans: https://fonts.google.com/specimen/Josefin+Sans
Inter: https://fonts.google.com/specimen/Inter
Gloock: https://fonts.google.com/specimen/Gloock
Montserrat: https://fonts.google.com/specimen/Montserrat
Montserrat Alternates: https://fonts.google.com/specimen/Montserrat+Alternates
Changa: https://fonts.google.com/specimen/Changa
Kanit: https://fonts.google.com/specimen/Kanit
Titillium: https://fonts.google.com/specimen/Titillium+Web=
Arimo: https://fonts.google.com/specimen/Arimo
Anton: https://fonts.google.com/specimen/Anton
Bebas Neue: https://fonts.google.com/specimen/Bebas+Neue
Prompt: https://fonts.google.com/specimen/Prompt
Space Grotesk: https://fonts.google.com/specimen/Space+Grotesk
Teko: https://fonts.google.com/specimen/Teko
Arvo: https://fonts.google.com/specimen/Arvo
Righteous: https://fonts.google.com/specimen/Righteous
Rajdhani: https://fonts.google.com/specimen/Rajdhani
IBM Plex Mono: https://fonts.google.com/specimen/IBM+Plex+Mono
IBM Plex Serif: https://fonts.google.com/specimen/IBM+Plex+Serif
Chakra Petch: https://fonts.google.com/specimen/Chakra+Petch
Poppins: https://fonts.google.com/specimen/Poppins
Space Mono: https://fonts.google.com/specimen/Space+Mono
Sora: https://fonts.google.com/specimen/Sora
Michroma: https://fonts.google.com/specimen/Michroma
Rubik Mono One: https://fonts.google.com/specimen/Rubik+Mono+One
MuseoModerno: https://fonts.google.com/specimen/MuseoModerno
Raleway: https://fonts.google.com/specimen/Raleway
Russo One: https://fonts.google.com/specimen/Russo+One
Old Standard TT: https://fonts.google.com/specimen/Old+Standard+TT
Saira: https://fonts.google.com/specimen/Saira
Mitr: https://fonts.google.com/specimen/Mitr
Jura: https://fonts.google.com/specimen/Jura
Jetbrains Mono: https://fonts.google.com/specimen/JetBrains+Mono
Work Sans: https://fonts.google.com/specimen/Work+Sans

**Comment by AlexCatarino** [comment]
@oussamanahdi , I am closing this issue since it's not clear what you want. :-)
