### ISSUE TITLE
Update Table to be Plugin; Store with other Libraries Data

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1157]
#### Expected Behavior
 - ML Libraries should be up to date with the primary library list.
 - https://www.quantconnect.com/docs/v2/writing-algorithms/machine-learning/key-concepts
 - https://www.quantconnect.com/docs/v2/writing-algorithms/key-concepts/libraries

#### Actual Behavior
ML Libs are old.

 - Create new dedicated plugin for ML libraries and put next to the other libraries so we see it while updating.
 - Update the ML table;
 -  DOCS_RESOURCES."/libraries/supported-ml-libraries.php"

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
https://github.com/QuantConnect/Documentation/commit/7e94ddefa0c811dd82ef1b5306387141a07c80ec
