### ISSUE TITLE
Local debugging in vscode extension requires language extensions to be installed

### ISSUE THREAD

**Issue by rjra2611** [QuantConnect/Documentation#1159]
#### Expected Behavior

Documentation should have a tutorial regarding local debugging requirements
#### Actual Behavior

We don't have this tutorial.
#### Local debugging requirements
- Python debugging
  - requires `Microsoft's` [python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) to be installed in vscode.
  ![image](https://user-images.githubusercontent.com/28739120/221960382-9b3854a8-9e7f-4fa5-8abb-f6b7d8409b72.png)

- C# debugging
  - requires `Microsoft's` [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) to be installed in vscode.
![image](https://user-images.githubusercontent.com/28739120/221959698-4143b1ae-fdb6-4f2f-9a7b-66a0449c8c08.png)

  - requires dotnet to be installed on the machine.
![image](https://user-images.githubusercontent.com/28739120/221959732-9df2b192-1c29-4c24-9a31-b42e13612180.png)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
The docs should also include the new `--debug` option from https://github.com/QuantConnect/lean-cli/pull/285

**Comment by DerekMelchin** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/ea8acebb926bd38d7d3279291d2c559ad62267a0
