### ISSUE TITLE
Lean CLI Julia Tutorial

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1160]
#### Expected Behavior

- Being able to use Julia in python algorithms
#### Actual Behavior

Custom docker file steps should be 
```
# Install Julia
RUN wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz && \
    tar zxvf julia-1.8.5-linux-x86_64.tar.gz && \
    rm julia-1.8.5-linux-x86_64.tar.gz
ENV PATH="/julia-1.8.5/bin:${PATH}"

# Install Julia package
RUN pip install --no-cache-dir julia==0.6.0

# Install Julia so it's ready for usage
RUN python -m julia.sysimage sys.so
```

Usage 
```csharp
        [Test]
        public void Julia()
        {
            AssertCode(
                @"
from julia import Julia
jl = Julia(sysimage=""/sys.so"")
from julia import Base

def RunTest():
    Base.sind(90)");
        }

```
#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Under [Custom Docker Images](https://www.quantconnect.com/docs/v2/lean-cli/projects/custom-docker-images), create a new H3: Example, and add a tutorial using Julia as example.
