### ISSUE TITLE
Universe Selection sequence contains no elements

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Documentation#117]
#### Expected Behavior
The algorithm should select ticker universe using both coarse and fine filters and return the top 80% by dollar volume (coarse filter) and then the top and bottom 10% of assets according to FCFYield, PERatio, BookValuePerShare, and PriceChange1M (fine filter).

#### Actual Behavior
Universe selection works as expected (log statements have returned symbols as expected) except when an error is thrown after 6/20/2018 
`2018-06-21 00:00:00 Runtime Error: Sequence contains no elements`

#### Potential Solution
Uncertain. The only starting point I can think of is when the error 
`Data for symbol VICI has been limited due to numerical precision issues in the factor file. The starting date has been set to 6/25/2018.` 
is thrown.

#### Reproducing the Problem
See backtest at this URL: https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_7abb411400c518989448e33f5323a9e8.html

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
@simonsonjack - what ended up being the resolution here?

**Comment by jaredbroad** [comment]
Moved to https://github.com/QuantConnect/Lean/issues/2848
