### ISSUE TITLE
Review Data Normalization + Universes

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1172]
#### Desired Behavior
Check to ensure cross-reference between standard and universe data selection for data normalization.
https://discord.com/channels/846109296973840424/1084362861012328458/1084670778001334452

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
We think that these sections explain it well:
https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/us-equity/requesting-data#11-Data-Normalization
https://www.quantconnect.com/docs/v2/writing-algorithms/universes/settings#02-Properties

If not, we might need to create a new section for Static Universes here:
https://www.quantconnect.com/docs/v2/writing-algorithms/universes/equity
to point out the setting of static universe come from the AddEquity arguments.

**Comment by AlexCatarino** [comment]
We have a cross-reference. This page:
https://www.quantconnect.com/docs/v2/writing-algorithms/universes/settings#07-Data-Normalization-Mode
points to 
https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/us-equity/requesting-data#11-Data-Normalization
