### ISSUE TITLE
Add documentation for a custom indicator

### ISSUE THREAD

**Issue by HalldorAndersen** [QuantConnect/Documentation#118]
Add a section to documentation on [Indicators ](https://www.quantconnect.com/docs/algorithm-reference/indicators) on how to construct a custom indicator.

**Comment by Pi-Rr** [comment]
Agree, that would be super helpful for the novice coder that are learning with QuantConnect :)

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/custom-indicators)
