### ISSUE TITLE
Adds Cancel Method to Insight Manager

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1182]
#### Expected Behavior
We document that the Insight Manager has a Cancel method to cancel active/open insights.

#### Actual Behavior
The documentation shows:
```
insight.CloseTimeUtc = algorithm.UtcTime - timedelta(seconds=1)
algorithm.Insights.Remove(insight)
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Document new methods from https://github.com/QuantConnect/Lean/pull/7127
