### ISSUE TITLE
Update IDE Section to Include Why Cookies are Neccessary

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1185]
User requests to include why cookies are necessary for the VSCode environment.  [cloud-platform/projects/ide](https://www.quantconnect.com/docs/cloud-platform/projects/ide) section of the documentation. 

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
https://www.quantconnect.com/docs/v2/cloud-platform/projects/ide#14-Cookies
