### ISSUE TITLE
Missing the Delay Indicator

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1213]
#### Expected Behavior

[Supported Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators) includes the [Delay indicator](https://github.com/QuantConnect/Lean/blob/master/Indicators/Delay.cs).

#### Actual Behavior

[Supported Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators) doesn't include the Delay indicator.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
The latest branch from `github-action-Writing-Algorithm-API-Ref-Code-Generator` is trying to remove the Delay indicator from the docs
![image](https://github.com/QuantConnect/Documentation/assets/38889814/bbcee714-68f9-4b1d-995f-d8e5518f8204)

**Comment by LouisSzeto** [comment]
Hi! I cannot reproduce this by running the indicator code gen.
