### ISSUE TITLE
Manual Beta Indicator Example Throws Error

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1216]
#### Expected Behavior

The code snippets in [Using B Indicator](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/beta#02-Using-B-Indicator) run without error

#### Actual Behavior

The code snippets on this page that use the `Beta` constructor throw
> Trying to dynamically access a method that does not exist throws a TypeError exception. To prevent the exception, ensure each parameter type matches those required by the 'int'>) method. Please checkout the API documentation.
  at Initialize
    self.b = Beta("SPY" in main.py: line 7
 No method matches given arguments for .ctor: (, )

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
The solution isn't quite right. We get an error

> Please register to receive data for symbol 'NONE 0' using the AddSecurity() function. in Indicators.cs:line 2211 Please register to receive data for symbol 'NONE 0' using the AddSecurity() function

**Comment by LouisSzeto** [comment]
Hi! I think this is not related to docs, but a LEAN issue. I’ve created https://github.com/QuantConnect/Lean/issues/7326
