### ISSUE TITLE
Automatic Option Assignments

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1221]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean/pull/7165
- We have a **Writing Algorithms > Reality Modeling > Options Models > Assignment** page
- The text in [Option Assignments](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-types/option-exercise-orders#06-Option-Assignments) is correct and links to the new **Assignments** page

#### Actual Behavior

Not currently documented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
- Option assignment is now a model which lives on the **Option**, following the pattern of fees/BPM/slippage/etc.
- The Option assignment model defaults to the `DefaultOptionAssignmentModel` on all options but can be overridden to `NullOptionAssignmentModel`/custom.
- The OptionAssignmentModel will be called by the QC backtesting & live paper brokerage only
- [Behavior change] before there was a random component to determine at what **time** an option would be assignment, now we will call the `IOptionAssignmentModel` every hour to get any assignments if required
