### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by kimasplund** [QuantConnect/Documentation#1229]
On https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/crypto-futures
the link under "See Also" is wrong.

[BasicTemplateCryptoFutureAlgorithm.py](https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/BasicTemplateCryptoFutureAlgorithm.cs)

should perhaps go to correct python file and not to BasicTemplateCryptoFutureAlgorithm.cs? :)

**Comment by DerekMelchin** [comment]
Hi @kimasplund,

The Python version of these files don't currently exist. See https://github.com/QuantConnect/Lean/issues/7182. When the C# versions are added to LEAN, we'll update these links in the docs. For now, we updated the link text to be `.cs` instead of `.py`.

Thanks
