### ISSUE TITLE
Review AddSecurity/Data and History API parameters

### ISSUE THREAD

**Issue by jhonabreul** [QuantConnect/Documentation#1236]
#### Expected Behavior

We document changes from https://github.com/QuantConnect/Lean/pull/7180

- We should review the documentation for the new `fillForward` parameter name (changed from `fillDataForward`) in the AddSecurity/Data APIs.
- Also check whether we need to add documentation for the new history API `fillForward` parameter in the remaining overloads [here](https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/history-requests).

#### Actual Behavior

`fillForward` parameter is only documented for one `History` overload.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Closed by 
- https://github.com/QuantConnect/Documentation/commit/bd57539c68e09c30abea82f47c639df64102d16e
- https://github.com/QuantConnect/Documentation/pull/1248
- https://github.com/QuantConnect/Documentation/pull/1249
