### ISSUE TITLE
More information about close time

### ISSUE THREAD

**Issue by michaelsrew** [QuantConnect/Documentation#124]
There should be more information about closing candles in daily resolution also in hour resolution as the questions comes up regularly.

choosing Resolution.Daily -> infotext/comment: Closing: 00:00
Resolution Chapter: when hour candle starts and when it closes
C#/Python Examples with comments
......

https://www.quantconnect.com/forum/discussion/1497/daily-trade-bar-close-time

**Comment by jaredbroad** [comment]
Closed in https://www.quantconnect.com/docs/key-concepts/understanding-time
