### ISSUE TITLE
Run All Code Generators Action Has an Ordering Issue

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1261]
#### Expected Behavior

After we add a new indicator to LEAN, the `Run All Code Generators` GitHub Action creates branches to add the new indicator to the [API Reference](https://www.quantconnect.com/docs/v2/writing-algorithms/api-reference) and to [Supported Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators).

#### Actual Behavior

The `Run All Code Generators` GitHub Action only adds the new indicator to the API Reference. 

To fix the issue, we need adjust `Writing-Algorithm-API-Ref-Code-Generator` so that at the bottom of it, it calls `Indicator-Reference-Code-Generator`

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by ac72cb3df3d8f2812b1844e73b66d23067318825
