### ISSUE TITLE
Document Forward Only Fill Model Example

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1286]
#### Expected Behavior

At https://github.com/QuantConnect/Lean/pull/7232 we've added example algorithms using a custom fill model which will only fill with data at or after the order submission time. This is to encourage more pessimistic fill models and eliminate the possibility to fill on old market data that may not be relevant, specially using multi resolutions or scheduled events

#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Closed by 791bfc22cd24d8ebb0d1a9a6dc04269e71aafa3f
