### ISSUE TITLE
Legacy issue: import Decimal in python

### ISSUE THREAD

**Issue by linkliang** [QuantConnect/Documentation#129]
https://github.com/QuantConnect/Documentation/blob/master/02%20Algorithm%20Reference/10%20Rolling%20Window/01%20Introduction.html
Line 75
This line should be removed since it only exists for backward compatibility, therefore new code should not import it.

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/310e0caac0cd0037eb9780ff4352cd400be084ae
