### ISSUE TITLE
C# Version of Get Price Model Data tutorial

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1299]
#### Expected Behavior

The [Get Price Model Data](https://www.quantconnect.com/docs/v2/research-environment/datasets/equity-options#09-Get-Price-Model-Data) tutorial is available in Python and C#

#### Actual Behavior

The tutorial currently only documents the Python version

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Replaced by https://github.com/QuantConnect/Documentation/issues/1608
