### ISSUE TITLE
Protective Call and Protective Put Option Strategies

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1317]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean/pull/7258 and https://github.com/QuantConnect/Lean/pull/7297
- [Option Strategies](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies) contains pages for Protective Call and Protective Put
- [Requesting Data](https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/equity-options/requesting-data) has a new H3 called **Helper Methods** that documents the `OutOfTheMoneyAmount` method. This H3 should also include `IsAutoExercised`, `GetPayOff`, and `GetIntrinsicValue` (not related to this PR)

#### Actual Behavior

Not currently documented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by 0b570bf45492b004c68b84a0db38c23ed4fcc3dd and 794c4367f4649a39307f3e9fea77e92499be26e7
