### ISSUE TITLE
Short Staddle and Short Strangle Option Strategies

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1318]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean/pull/7264 and https://github.com/QuantConnect/Lean/pull/7300
- [Straddle](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/straddle) explains long straddle and short straddle
- [Strangle](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/strangle) explains long strangle and short strangle

These pages follow the pattern of [Call Butterfly](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/call-butterfly), which documents the long and short version of a strategy on a single page.

#### Actual Behavior

We currently only document the long version of these strategies.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/pull/1470
