### ISSUE TITLE
Naked Call and Naked Put Option Strategies

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1328]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean/pull/7231 and https://github.com/QuantConnect/Lean/pull/7298
- In [Option Strategies](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies), we have a Naked Call page and a Naked Put page

#### Actual Behavior

Undocumented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
TODO: Add image to [Strategy Payoff](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/naked-call#03-Strategy-Payoff)

**Comment by AlexCatarino** [comment]
TODO: Add image to [Strategy Payoff](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/naked-put#03-Strategy-Payoff)

**Comment by AlexCatarino** [comment]
Closed by #1472
