### ISSUE TITLE
Covered Call and Covered Put Option Strategies

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1342]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean/pull/7296
- [Covered Call](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/covered-call) uses `OptionStrategies.CoveredCall`

We document the changes from https://github.com/QuantConnect/Lean/pull/7297
- We have a **Covered Put** page in [Option Strategies](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies)

#### Actual Behavior

Undocumented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Addressed by https://github.com/QuantConnect/Documentation/commit/08b66a80920b7d597e9ac0a1fab5310dbeeaa6bc
Not closing this issue because we need the payoff image for the Covered Put.
