### ISSUE TITLE
Object Store Live Behavior

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1346]
Object store page includes a note about the live trading behavior.
https://www.quantconnect.com/forum/discussion/15223/accessing-object-store-in-live-trading/p1

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
We note the live trading behavior in the introduction:
https://www.quantconnect.com/docs/v2/writing-algorithms/object-store#01-Introduction

**Comment by AlexCatarino** [comment]
New section: https://www.quantconnect.com/docs/v2/writing-algorithms/object-store#13-Live-Trading-Considerations
