### ISSUE TITLE
Historical Indicator Values

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1363]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean/pull/7314
- [Add Data](https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/rolling-window#03-Add-Data) shows 
     - You can add data at a specific index (self.close_window[0] = 10.0)
     - If the window is too small for the index you pass, the window grows in size up to the index you provide. Empty indices have default values, but Window.Count remains the same
- A new "Adjust Size" H3 on https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/rolling-window 
     - Shows how to change the windows size with its new `Size` property.
     - Explains that if you index the window past its size, it resizes the window.

- [Combine with Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/rolling-window#07-Combine-with-Indicators) 
    - Explains that the default window size is 2
    - Shows how to use the window property in the indicator class instead of an external RollingWindow

- [Get Indicator Values](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/key-concepts#08-Get-Indicator-Values) **> Historical Indicator Values**
    - Explains the `Previous.Value` property
    - Shows how to iterate through the historical values by simply iterating through the indicator objects
    - Shows how to index the indicator to get historical values
    - Shows how to use the window property in the indicator class instead of an external RollingWindow
    - Uses a BB indicator and demonstrates how to `bb.Window` and `bb.MiddleBand.Window` to access the historical values and the EndTime of those respective values

- [Check Readiness](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/key-concepts#06-Check-Readiness) explains that the indicator can be ready even when the internal RollingWindow objects that hold historical values are not ready

- The following sections explain the default historical window size is 2 and show how to adjust the window size:
  - [Create Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/key-concepts#05-Create-Indicators)
  - [Create Manual Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/manual-indicators#03-Create-Manual-Indicators)
  - [Create Automatic Indicators](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/automatic-indicators#03-Create-Automatic-Indicators)

#### Actual Behavior

Undocumented 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
https://github.com/QuantConnect/Documentation/commit/fba7f76249d1728b9e8e2482a3a266a1b081187c covers Add Data and Adjust Size parts.
