### ISSUE TITLE
Oanda API not available in Europe

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1370]
#### Expected Behavior

https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/oanda explains that the Oanada API isn't available in Europe.

[Related Discord thread](https://discord.com/channels/846109296973840424/846117654267166761/1121423918713032715)

#### Actual Behavior

Undocumented.
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
European residents need to open accounts with OANDA TMS Brokers S.A. and it doesn't offer REST API.

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/53cf2f63c76d85cee29b6e0d35270cf3f908ab2d
