### ISSUE TITLE
Mention Latex Support in Cloud / Community / Forum

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1378]
#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/1731ebee07d90aa7e345f056f7016047efa06c94
