### ISSUE TITLE
Fundamental Field Default Periods Incorrect

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#138]
https://raw.githubusercontent.com/QuantConnect/Lean/master/Common/Data/Fundamental/Generated/MultiPeriodValueTypes.cs

FCF periods in years; documentation shows 1month

**Comment by DerekMelchin** [comment]
Solved in [US Fundamentals dataset listing](https://www.quantconnect.com/datasets/morning-star-us-fundamentals).
![image](https://user-images.githubusercontent.com/38889814/153512931-defbd57f-bd76-4b87-a9dc-ec2b67207510.png)
