### ISSUE TITLE
`include` errors on some of the indicator reference pages

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1386]
#### Expected Behavior

The docs don't display any PHP errors.

#### Actual Behavior

This error message
> Warning: include(/tmp/docs/5aa6d2628634caa9b19fb38d826c4efebb916c5b/Resources/qcalgorithm-api/filteredidentity.html): failed to open stream: No such file or directory in /tmp/docs/5aa6d2628634caa9b19fb38d826c4efebb916c5b/Resources/indicators/using-indicator.php on line 49 Warning: include(): Failed opening '/tmp/docs/5aa6d2628634caa9b19fb38d826c4efebb916c5b/Resources/qcalgorithm-api/filteredidentity.html' for inclusion (include_path='/var/www/beta/core/libraries/Google:/var/www/beta:.:/usr/share/php') in /tmp/docs/5aa6d2628634caa9b19fb38d826c4efebb916c5b/Resources/indicators/using-indicator.php on line 49

shows up on [FilteredIdentity](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/filtered-identity), [HeikinAshi](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/heikin-ashi), and [HilbertTransform](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/hilbert-transform).

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
I checked 6 of the pages for candlestick patterns ([example](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/candlestick-patterns/breakaway)) and they all had this error too

**Comment by AlexCatarino** [comment]
Fixed by https://github.com/QuantConnect/Documentation/commit/b5e986629fb370dcce062386742ee85bd5672800
