### ISSUE TITLE
QC API Responses

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1387]
#### Expected Behavior

The **Responses** section of the pages in the [API Reference](https://www.quantconnect.com/docs/v2/cloud-platform/api-reference) chapter are correct.

#### Actual Behavior

[Responses](https://www.quantconnect.com/docs/v2/cloud-platform/api-reference/live-management/read-live-algorithm/orders#03-Responses) shows that the `orders` key refers to a dictionary `{ }`, but it should be a list since the endpoint returns data on multiple orders. 

We have been working on the API because of the Local Platform so some other responses might be invalid, not just this particular example.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
The Live Orders case fixed by https://github.com/QuantConnect/Documentation/commit/808853fb581b052e663878f0fe7b6d31dce63028
