### ISSUE TITLE
Missing Market Hours Landing Page

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1392]
#### Expected Behavior

If you are on the [Futures](https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/futures) page and click the **Market Hours** button, it directs you to a landing page that lists all of the Futures markets.

#### Actual Behavior

The https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/futures/market-hours page is empty

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/82e13a6ecd88018fb8502728f3d43951a51fc881
