### ISSUE TITLE
Wolverine Order Properties

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1394]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/Lean.Brokerages.Wolverine/pull/11 and https://github.com/QuantConnect/Lean/pull/7355
- [Orders](https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/brokerages/supported-models/wolverine#03-Orders) and [Orders](https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/wolverine#05-Orders) explain the `WolverineOrderProperties`

#### Actual Behavior

Undocumented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/4a34586e03c8a1478f87ce9fdfc1f3c4c535beaa
