### ISSUE TITLE
Revise Documentation for Upgrading Classic Algorithms

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Documentation#140]
Alpha Streams documentation regarding upgrading classic algorithms needs to be updated:
 - Remove references to FrameworkBridgeAlgorithms
 - Discuss Flat Insights
 - Mention why it is important to emit insights even though trades will do this already

**Comment by DerekMelchin** [comment]
Flat insights discussed in docs v2 [here](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/alpha/key-concepts#06-Insights).
