### ISSUE TITLE
Link to Live Features Algorithm Example in Live Trading Notifications

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1402]
#### Expected Behavior
More complete code examples in live trading notifications
https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/LiveFeaturesAlgorithm.py
https://www.quantconnect.com/docs/v2/writing-algorithms/live-trading/notifications

**Comment by jaredbroad** [comment]
Including sending attachmenets

```
During the algorithm initialization, the following exception has occurred: System.ArgumentException: ConvertToDictionary cannot be used to convert a <class 'list'> into PyDict. Reason: object is not a dict
 ---> System.ArgumentException: object is not a dict
   at Python.Runtime.PyDict..ctor(PyObject o)
```

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/284312d13ab039a34a564eae30b4ca5ba8434a98
