### ISSUE TITLE
Project folder in IDE vs. CLI root folder missunderstanding

### ISSUE THREAD

**Issue by jhonabreul** [QuantConnect/Documentation#1409]
#### Expected Behavior

Users should open the project folder in their selected IDE but `lean` commands should always be run in the CLI root folder.

#### Actual Behavior

Users might be missunderstanding the documentation for [debugging](https://www.quantconnect.com/docs/v2/lean-cli/backtesting/debugging#06-C-and-VS-Code). By "Open the directory containing the Main.cs file in a new VS Code window" they might think the commands should also be run in that same folder, as [this user](https://github.com/QuantConnect/lean-cli/issues/284#issuecomment-1437104638).

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Closed by https://github.com/QuantConnect/Documentation/pull/1420
