### ISSUE TITLE
`lean data generate` options

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1417]
#### Expected Behavior

We document the changes from https://github.com/QuantConnect/lean-cli/pull/348 and https://github.com/QuantConnect/Lean/pull/7390
- Update https://www.quantconnect.com/docs/v2/lean-cli/datasets/generating-data#04-Run-the-Generator 
- Update https://www.quantconnect.com/docs/v2/lean-cli/api-reference/lean-data-generate

#### Actual Behavior

Undocumented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Missing options:
https://github.com/QuantConnect/Documentation/blob/master/05%20Lean%20CLI/99%20API%20Reference/23%20lean%20data%20generate/03%20Options.html#L71
