### ISSUE TITLE
Review Properties in Indicator Reference Pages

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1418]
#### Expected Behavior

The code snippets in the indicator reference pages run without error.

#### Actual Behavior

The [Using VP Indicator](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/volume-profile#02-Using-VP-Indicator) tutorial uses `.Current.Value` for every property, but it causes issues as seen in [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_264443a33f3c2817412ca24131c06a75.html). There are probably other indicator reference pages that have this same issue.

[Related Discord thread](https://discord.com/channels/846109296973840424/846467760119873617/1130585533614149754)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/9fb28de05cbdf7bcee2a55e5cac76c2868d18fc3
