### ISSUE TITLE
Documents Trailing stop orders

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1423]
See https://github.com/QuantConnect/Lean/pull/7402

**Comment by AlexCatarino** [comment]
Added by https://github.com/QuantConnect/Documentation/commit/6c9ffa4ff4ca609fa6698808501f38bc364d65e3 
Leaving this issue open since we need the images.

**Comment by oussamanahdi** [comment]
Trailing stop images
[trailing-stop-charts.zip](https://github.com/QuantConnect/Documentation/files/12234443/trailing-stop-charts.zip)

**Comment by DerekMelchin** [comment]
Revised images:
[trailing-stop-charts (1).zip](https://github.com/QuantConnect/Documentation/files/12293522/trailing-stop-charts.1.zip)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/066730c590955aecad3deba2eced3562bb454630
