### ISSUE TITLE
Add documentation for custom HTML template file and CSS override file in Report Generator

### ISSUE THREAD

**Issue by Marinovsky** [QuantConnect/Documentation#1425]
A new feature has been implemented in LEAN that now allows the users to provide a custom HTML template file and CSS override file to use in the reports generated(see LEAN pr's #7401 and #7410). The given HTML template file replaces the default template and the CSS override file, as its name says, override default CSS stylesheet. Now, the next step is add the required documentation to brief the users on how to use this new feature. 
#### CSS Override file usage
-CLOUD usage: To override the default CSS stylesheet, the user needs to first create a CSS file in the workspace and write in it the changes to be overridden (in CSS language of course). Once the CSS file has been created and saved, the user should run the backtest and once it has loaded, the user will click the button `Report` to generate the report. Below, screenshots of an example are shown:

**Edit: cloud usage requires creating `report.html/report.css` file names explicitly** any other name will be ignored.

![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/60dc28b9-12d9-41b7-b995-f7ad96258d2f)
2. Run the backtest
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/cd66e45b-0869-445c-a02c-855da609a916)
3. Click on the button labeled `Report` and request a report
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/8cbb4188-f5f2-41a1-a49a-be1e9783e70a)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/62755da8-07ee-4271-9d95-7f327e0f5d0a)

-CLI usage: To override the default CSS stylesheet, the user needs to first create a CSS file in the working directory and write in it the changes to be overridden (in CSS language of course). Once the css file has been created and all the desired changes are written there, the user will run the following command from its terminal (in the working directory): `lean report --css <name of the CSS file>`(Other optional arguments can be included of course). For example, if the user is working in `C:\LEAN_CLI\` and the name of the CSS override file is `report_override.css`, the command it should run would be `lean report --css report_override.css`. Below, screenshots of the mentioned example are shown:
1. Create a CSS file in the working directory and write the CSS changes to be applied (I'm using Notepad++ editor)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/8e201520-7c31-413e-8feb-744ab38fd37a)
2. Open a terminal in the working directory
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/baff3630-d603-4b79-84e4-c03d8826be61)
5. Write the following command `lean report --css report_override.css` and press enter
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/6b101267-b79b-46c6-a839-a3a31cfc5995)
6. Open the report generated
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/e8df1607-229f-4d8e-b659-3d236a2e960e)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/c1ffbec9-770d-4d6c-ab60-2d567b583be4)
#### Custom HTML template usage
Though the design of the HTML template is up to the user, the HTML needs to fulfill these following requirements:
1. In order to display certain Report Element, the user needs to add the respective _key_ in its HTML file (see https://github.com/QuantConnect/Lean/blob/master/Report/ReportKey.cs for information about each key). For example, if the user wants to add the _Rolling Beta_ chart in its report, their custom HTML file should contain the _key_ = `{{$PLOT-BETA}}` in the part were this chart is expected to be displayed
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/fc5c6f03-18ce-4416-8ea4-b9b8eb937a88)
2. To display the crisis plots, the user needs to add the template they will follow as comment in the custom HTML template file. However, the comment should follow the next pattern: `<!--crisis <the HTML template for the crisis plots> crisis-->` as shown in the image below
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/e1be4a02-43e5-448f-bb0e-2b74eea4684a)
3. To display each algorithm parameter, the user needs to add the HTML template each entry will follow as comment in the custom HTML template file. However, the comment should follow the follow the next pattern: `<!--parameters <the HTML template for each parameter entry> parameters-->` as shown in the image below
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/5e148f76-351b-4e50-9738-1fad7f25032a)
On the other hand, each key and value name in the template should have the same format `{{$KEY<number>}}` and `{{$VALUE<number>}}`. If the user wants to display three parameters per row then it should define three keys with the names `{{$KEY0}}`, `{{$KEY1}}`, `{{$KEY2}}` and their respective values `{{$VALUE0}}`,`{{$VALUE1}}`,`{{$VALUE2}}`

- CLOUD usage: To use a custom HTML template in the report generated the user needs to first create a HTML file in the workspace and write in it the template to be used in the report generated. Then, the user will run the backtest and wait until this have already loaded. Finally, the user will press the button labeled as `Report` and will request a report. Below, screenshots of an example are shown

**Edit: cloud usage requires creating `report.html/report.css` file names explicitly** any other name will be ignored.

1. Create a HTML template in the workspace and save it
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/fd1ed2b0-75c9-4093-88b9-96df87fec4ba)
2. Run the backtest
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/e4c431ba-859c-4038-a5ca-f5ffc39f619c)
3. Press the button _Report_ and request a report
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/f38f1f39-83cf-4f32-812b-3c8bf1e65f4e)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/abfb6766-b00b-4416-ba73-d11f07ab80d2)

- CLI usage: To use a custom HTML template in the report generated, the user needs to first create a HTML file in the working directory and write in it the template to be used in the report generated. Then, a terminal should be opened in the same working directory. When the terminal is open the user should write the following command: `lean report --html <name of the custom HTML template file>` and press enter. For example, if the name of the custom HTML template file is `template_custom.html` and the user working directory is `C:\Lean_CLI\` the user needs to run the command `lean report --html template_custom.html`(Other optional arguments can be also included) in a terminal in `C:\Lean_CLI\`. Below, screenshots of the mentioned example are shown:
1. Create a HTML file in your working directory and write in it the desired template you would like to use in the reports generated(in HTML code of course)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/5db7105a-44e2-48db-99a0-1dba92d275c5)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/5bd7ee33-5d7e-4961-b3eb-d9c5b631c1de)

3. Open a terminal in your working directory, in this case: `C:\Lean_CLI\`
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/8b6b4bd1-f3c2-4c61-976b-298b2d9e747c)
5. Run the following command: `lean report --html template_custom.html`
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/e4fad9f0-c11b-43e5-be17-02c06480614f)
6. Open the file `report.html`, located in your current working directory
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/aee40352-558a-48f2-b127-6a9ae9e9bc05)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/1eee8f49-db9c-4bbf-bc0e-56cf9a06de11)
![imagen](https://github.com/QuantConnect/Documentation/assets/47573394/117f7ba5-27eb-4ee8-8575-df9cfabcdbd9)

For more information, please see https://github.com/QuantConnect/Lean/blob/master/Report/Report.cs
#### Actual Behavior

There is no documentation
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by oussamanahdi** [comment]
html with custom logo and report.css with a fix to allow using logos of any dimensions without breaking out of the header

[custom report.zip](https://github.com/QuantConnect/Documentation/files/12234078/custom.report.zip)

![CleanShot 2023-08-01 at 22 02 48@2x](https://github.com/QuantConnect/Documentation/assets/79997186/34700bad-cf7e-48e5-aa2f-3fb0aaafd55c)

**Comment by DerekMelchin** [comment]
We also need to ensure we have these changes:
- https://github.com/QuantConnect/Lean/pull/7410 / https://github.com/QuantConnect/lean-cli/pull/351
    - Update https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/report and https://www.quantconnect.com/docs/v2/lean-cli/reports to explain how to provide a custom HTML template
    - Update Options to include the new `--html` option
- https://github.com/QuantConnect/Lean/pull/7401 / https://github.com/QuantConnect/lean-cli/pull/349
    - Add a new Parameters H3 to the bottom of https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/report and https://www.quantconnect.com/docs/v2/lean-cli/reports that explains the new table, how to hide it, and how it transforms your parameter names. Also add this new information to https://www.quantconnect.com/docs/v2/lean-cli/api-reference/lean-report#02-Description
    - Update Supported File Types and Supported File Types to include CSS and HTML files
    - Update Options to include the new `--css` option

**Comment by AlexCatarino** [comment]
Reopen for discussion:

"Customize the Report HTML" should be on the [Backtesting > Report](https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/report) page, e.g. H3 "Customize the Report HTML". The [Backtesting > Results > Report](https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results#09-Reports) H3 has a link to that page where users would see the customization option.

[Backtesting > Report](https://www.quantconnect.com/docs/v2/lean-cli/reports) on Lean CLI could follow the same pattern (add a H3).

I think the "problem" is that Local Platform, since Reports only lives in [Backtesting > Results > Report](https://www.quantconnect.com/docs/v2/local-platform/backtesting/results).
