### ISSUE TITLE
Document RangeConsolidator

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1427]
#### Expected Behavior
New range consolidator (see https://github.com/QuantConnect/Lean/pull/7385) is documented under the [Consolidating Data](https://www.quantconnect.com/docs/v2/writing-algorithms/consolidating-data/) section.

#### Actual Behavior
Not documented yet.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Still need to document the ClassicRangeConsolidator
