### ISSUE TITLE
Update YAML for Optimization API

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1439]
#### Expected Behavior
QC REST API is fully documented.

#### Actual Behavior
Missing optimization

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/2b853c84ac1914b4f297deeb5ccde7a407cae3eb
