### ISSUE TITLE
Object Store DataFrame Examples

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1448]
#### Expected Behavior

[Writing Algorithms > Object Store](https://www.quantconnect.com/docs/v2/writing-algorithms/object-store) and [Research Environment > Object Store](https://www.quantconnect.com/docs/v2/research-environment/object-store) show how to save and load DataFrames for Python

#### Actual Behavior

They don't currently show examples of saving/loading Python DataFrames

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/f2e6433693f62fd46ce53a25aaf808708d991f39
