### ISSUE TITLE
Add Collective2 to Live Trading > Signal Exports

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1457]
#### Expected Behavior
Collective2 is documented under [Signal Exports](https://www.quantconnect.com/docs/v2/writing-algorithms/live-trading/signal-exports).

#### Actual Behavior
Undocumented.
See: https://github.com/QuantConnect/Lean/pull/7448

#### Note:
Similar to [Numerai](https://www.quantconnect.com/docs/v2/writing-algorithms/live-trading/signal-exports/numerai).
Collective2 doesn't support all futures, and we get this error: 

```
Collective2 API returned the following errors: "errors": [
"Item #1 in positions list: Unknown symbol",
"Item #2 in positions list: Unknown symbol"
],"title": "Unable to setDesiredPositions","message": "There were problems with your request."
```

Here is the list: [symbology_futures](https://www.collective2.com/symbology_futures.htm). Users need to contact them.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
https://www.quantconnect.com/docs/v2/writing-algorithms/live-trading/signal-exports/collective2
