### ISSUE TITLE
Update "Apply QCC to Invoices"

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1460]
#### Expected Behavior
Refers to the current state:
![capture](https://github.com/QuantConnect/Documentation/assets/6889033/277b73f2-2a8c-4c0c-92dd-5ac2d020b99a)

#### Actual Behavior
[Apply QCC to Invoices](https://www.quantconnect.com/docs/v2/cloud-platform/organizations/credit#07-Apply-QCC-to-Invoices) teaches the old way to apply QCC.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/128885d49f57f92c10f0e2e962b348d114bb09b5
