### ISSUE TITLE
Result Log Filter

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1473]
#### Expected Behavior
Log filter is documented.

https://github.com/QuantConnect/Documentation/assets/6889033/afb83919-47ee-4f63-9f47-0ec935469ce4

#### Actual Behavior
New feature. Not documented yet on:
https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results#12-Logs
https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/results#10-Logs

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
DONE:
- Added to https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/results#10-Logs
- Added to https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results#12-Logs 

TODO: 
- After the UX bug is fixed, add a gif demo to https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results#12-Logs
- After latest version of Local Platform ships, add to https://www.quantconnect.com/docs/v2/local-platform/backtesting/results#12-Logs
