### ISSUE TITLE
Trading Technologies Getting Started

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1484]
#### Expected Behavior

- Creating API keys
	- Navigate to the TT 'Setup' page
	- Under the 'Users' left panel menu
	- Select a specific user, and under the 'App Keys' tab select 'New'
	- TT will provide the credentials in the following format '{App Key}:{App Secret}'

- Creating FIX Session
	This step will provider the 'Session Password' & 'Routing Sender' (Remote Comp ID for TT) configurations for the QC live wizard
	- Navigate to the TT 'Setup' page
	- Under the 'FIX Sessions' left panel menu under 'More'
	- Select 'New FIX Session' and fill in the form

#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Screenshots: https://quantconnect.slack.com/archives/D012WHWMPT2/p1695398720634899

**Comment by AlexCatarino** [comment]
See [Create TT User](https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/trading-technologies#14-Create-TT-User)
