### ISSUE TITLE
Update Organization Support to Document New AI Feature

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1496]
#### Expected Behavior
Includes AI feature to Support Tickets

#### Actual Behavior
Doesn't explain this new AI feature. We only document AI for console.

#### Proposed Solution
[Open New Tickets](https://www.quantconnect.com/docs/v2/cloud-platform/organizations/support#06-Open-New-Tickets):
After `Send`, we inform that Mia will answer the question, and we will see this option at the bottom:

![capture](https://github.com/QuantConnect/Documentation/assets/6889033/e24fb7b9-9bd0-42f2-8203-59269fd54dfb)

If the AI answer is accepted, the ticket is closed and is counted as [AI Support](https://www.quantconnect.com/docs/v2/cloud-platform/organizations/support#11-AI-Support). If we ask for human support, the [Ticket Quotas](https://www.quantconnect.com/docs/v2/cloud-platform/organizations/support#10-Ticket-Quotas) is observed.

I think we could merge the AI Support and Ticket Quotas tables under Ticket Quotas where one column says AI and another Human, and AI Support should come before Ticket Quotas (?)

Also, we need to update AI Support because it's not only in the console now, and explain that both console and support counts to its quota.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Done 
- https://www.quantconnect.com/docs/v2/cloud-platform/organizations/support#06-Open-New-Tickets
- https://www.quantconnect.com/docs/v2/cloud-platform/organizations/support#10-Ticket-Quotas
