### ISSUE TITLE
New Fundamental Data

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1515]
#### Expected Behavior

- Document the behavior of the new fundamental data. See https://github.com/QuantConnect/Lean/pull/7490
  - Single fundamental selection & data type (fine+coarse merge)
       - If not available double values will be Nan, and decimals 0
  - New data type uses double (vs previously decimals) for speed and memory footprint.
  - History requests support
  - QCAlgorithm.Fundamentals() API, provides fundamental data for the given symbol/s
  - Delisted companies now included
  - Important to note that users should not keep a direct reference to the fundamentals sub properties classes (like `IncomeStatement`), since these are reused. It's safe to keep a reference to the Fundamental instance itself.
  - We've also added QCAlgorithm.CIK() API, Central Index Key to help identify an asset, like we have ISIN/SEDOL/etc

- Remove/deprecate existing old coarse/fine/selection documentation
#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/77decf4921913d58eff19597c5fb5e1ce983a7bd
