### ISSUE TITLE
Add section about `MarketImpactSlippageModel`

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Documentation#1522]
#### Expected Behavior
Add a new section under Writing Algorithm -> Reality Modeling -> Slippage -> Supported Models for `MarketImpactSlippageModel`
Refer to https://github.com/QuantConnect/Lean/pull/7513

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
@LouisSzeto  Please add as much relevant information as possible to this issue. As the author you're the best person to write the documentation for it. Include code snippet examples and bullet descriptions of how the model works.
