### ISSUE TITLE
Asynchronous Universe Selection

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1527]
#### Expected Behavior

- Document new Asynchronous Universe selection. See https://github.com/QuantConnect/Lean/pull/7556
    - `UniverseSettings.Asynchronous = true;` should be set before creating the universes (AddOption -> creates option chain universe)
    - if using `Option.SetFilter(strikes/expiration)` we automatically enable asynchronous Universe Selection. Note: not if using `Option.SetFilter(func)`, requires setting the `UniverseSettings`
#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
See: https://github.com/QuantConnect/Documentation/issues/1584
