### ISSUE TITLE
Shortable Provider Improvements

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1531]
#### Expected Behavior

- Document improvements made at https://github.com/QuantConnect/Lean/pull/7579
- Update https://www.quantconnect.com/datasets/us-equities-short-availability & add new IB short availability data set
#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
The [dataset page](https://www.quantconnect.com/datasets/us-equities-short-availability) was updated.
Docs updated (https://github.com/QuantConnect/Documentation/commit/65cb25f0ae89a436cfea198eb95812b8e134704b) to reflect new constructor overload for `LocalDiskShortableProvider`.

TODO: Add H3 for `InteractiveBrokersShortableProvider` after `LocalDiskShortableProvider`. Note that 
InteractiveBrokersShortableProvider -> LocalDiskShortableProvider("interactivebrokers")
