### ISSUE TITLE
Create ByBit Plugin ReadMe.

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1533]
#### Expected Behavior
Brokerage plugins have a nice landing page when you open their github repo;

#### Actual Behavior
No readme defined for how to use bybit plugin
https://github.com/QuantConnect/Lean.Brokerages.ByBit

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Lean.Brokerages.ByBit/pull/10
