### ISSUE TITLE
Algorithm's Risk-Free Interest Rate Model 

### ISSUE THREAD

**Issue by jhonabreul** [QuantConnect/Documentation#1537]
#### Expected Behavior

A risk-free interest rate model can now be set to the algorithm for it's usage in indicators, statistics and potentially other calculations: https://github.com/QuantConnect/Lean/pull/7594

- `RiskFreeInterestRateModel` interface and implementing classes:
    - `InterestRateProvider`.
    - `ConstantRiskFreeInterestRateModel`.
    - `FuncRiskFreeInterestRateModel`.
- `QCAlgorithm.RiskFreeInterestRateModel` property and `QCAlgorithm.SetRiskFreeInterestRateModel` setter

#### Actual Behavior

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/CustomMarginInterestRateModelAlgorithm.py#L29
