### ISSUE TITLE
Indicator Reference Page Errors

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1540]
#### Expected Behavior

- There no PHP errors in the docs
- There are no punctuation errors in the docs
- There is an image that visualizes the indicator values
- The Introduction explains what the indicator is and how it's calculated

#### Actual Behavior

- The indicator reference pages ([example](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/correlation)) have the following PHP error:
> Warning: include(/tmp/docs/9045b53028ed528cc5895ec5735b784a35d46e54/Resources/qcalgorithm-api/correlation.html): Failed to open stream: No such file or directory in /tmp/docs/9045b53028ed528cc5895ec5735b784a35d46e54/Resources/indicators/using-indicator.php on line 52 Warning: include(): Failed opening '/tmp/docs/9045b53028ed528cc5895ec5735b784a35d46e54/Resources/qcalgorithm-api/correlation.html' for inclusion (include_path='/var/www/beta/core/libraries/Google:/var/www/beta:.:/usr/share/php') in /tmp/docs/9045b53028ed528cc5895ec5735b784a35d46e54/Resources/indicators/using-indicator.php on line 52

- There are punctuation errors in the docs (In this example, there should be no comma after TradeBar.)
> To manually update the indicator, call the Update method with a TradeBar, or QuoteBar.

- This [Visualization](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/correlation#03-Visualization) is not showing the correct image

- This [Introduction](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/alpha#01-Introduction) doesn't define what the Alpha indicator is and how it's calculated, yet the definition is in LEAN.

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Indicator Meta Description
1 - Trim to 130 chars:
2 - Remove see tag: `<see cref=\"T:QuantConnect.Indicators.TargetDownsideDeviation\" />` -> `QuantConnect.Indicators.TargetDownsideDeviation`

**Comment by AlexCatarino** [comment]
Closed. Code gen will fix the Alpha description (see https://github.com/QuantConnect/Lean/pull/7630).
