### ISSUE TITLE
Helpful Links to Algorithm Lab pages

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1544]
#### Expected Behavior

The menu items in the docs (for example, "Organization > Home" in [View Billing Information](https://www.quantconnect.com/docs/v2/cloud-platform/organizations/billing#03-View-Billing-Information)) have a hyperlink to the actual page.

#### Actual Behavior

It's just bolded in the docs, members have to manually navigate to get to the page.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by ee867f9
