### ISSUE TITLE
Glossary Updates

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1552]
#### Expected Behavior

The glossary contains definitions for risk free interest rate and sortino ratio

#### Actual Behavior

Not defined

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by 2f16190
