### ISSUE TITLE
Example Algorithms in Both Languages in Dataset Listings

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1553]
#### Expected Behavior

The **Example Applications** section of the dataset listings have an example algorithm for Python and C#. Only one of the example algorithms should display (waiting on UX feature)

#### Actual Behavior

Many of the dataset listings only show a Python algorithm in the Example Applications section

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by ashutoshrana171** [comment]
Added examples for the following data sets under the example application section :
- [x] US Equity Coarse Universe
- [x] US ETF Constituents
- [x] US Fundamental Data
- [x] US Equities Short Availability
- [x] Algoseek US Equities
- [x] Algoseek US Options
- [x] Algoseek US Futures
- [x] Algoseek US Future Options
- [x] Algoseek US Index Options
- [x] Tiingo News Feed
- [x] Benzinga News Feed
- [x] ExtractAlpha Estimize
- [x] Kavout Composite Factor Bundle 
- [x] ExtractAlpha Cross Asset Model
- [x] ExtractAlpha Tactical
- [x] Quiver Quantitative Twitter Followers
- [x] Brain Language Metrics on Company Filings
- [x] Brain ML Stock Ranking
- [x] Brain Sentiment Indicator
- [x] RegAlytics US Regulatory Alerts - Financial Sector
- [x] Smart Insider Corporate Buybacks
- [x] Quiver Quantitative Insider Trading
- [x] Quiver Quantitative WallStreetBets
- [x] Quiver Quantitative Corporate Lobbying
- [x] Quiver Quantitative US Government Contracts
- [x] Quiver Quantitative CNBC Trading
- [x] Quiver Quantitative Wikipedia Page Views
- [x] Quiver Quantitative US Congress Trading
- [x] US SEC Filings
- [x] US Federal Reserve (FRED)
- [x] Nasdaq Data Link
