### ISSUE TITLE
Next Day Formatting

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1558]
#### Expected Behavior

The start and end times in the market hours pages are valid.

#### Actual Behavior

![image (1)](https://github.com/QuantConnect/Documentation/assets/38889814/92228748-637d-4f8c-b6b4-bc269660009a)
https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/index-options/market-hours/vix

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by 61970ec1ce01838ced977342f215aa07541f8f40

**Comment by AlexCatarino** [comment]
Fixed by https://github.com/QuantConnect/Documentation/commit/b9dca3a6be08786e3e842c47b7a1486b9953d2dd
