### ISSUE TITLE
Futures Contract Rollovers

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1562]
#### Expected Behavior

These pages/sections explain how to perform contract rollovers:
- https://www.quantconnect.com/docs/v2/writing-algorithms/universes/futures
- https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/futures/handling-data#09-Symbol-Changes

These locations also explain what time the contracts switch for both backtesting and live trading.

#### Actual Behavior

Not fully documented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by ae2cb79

**Comment by AlexCatarino** [comment]
Closed by 9f55a50
