### ISSUE TITLE
Common error: Please make sure Docker is installed and running

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1563]
#### Expected Behavior

The docs explain how to overcome this common error.

#### Actual Behavior

Two cases:
1: (already documented)
```
You are trying to use a command which needs to run the LEAN engine locally, which always happens in a Docker container. Make sure Docker is running if you installed it already, or visit Install Docker if you haven't.
```
2: (not documented)
```
Your venv probably has a non standard docker path or no docker access. Please uninstall and reinstall docker.
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Fixed by 1e5fca3e18ffc9813d270ad4fa5ea730db8818b9
