### ISSUE TITLE
Automatically Select Best Node

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1565]
Add info about the selector in the Resources and Project super sections. Its a super common bug.
https://www.quantconnect.com/docs/v2/cloud-platform/organizations/resources#02-Backtesting-Nodes
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
The information is now found at
https://www.quantconnect.com/docs/v2/cloud-platform/organizations/resources#02-Backtesting-Nodes
https://www.quantconnect.com/docs/v2/cloud-platform/organizations/resources#03-Research-Nodes
https://www.quantconnect.com/docs/v2/cloud-platform/organizations/resources#04-Live-Trading-Nodes
and they link to
https://www.quantconnect.com/docs/v2/cloud-platform/projects/ide#07-Manage-Nodes
