### ISSUE TITLE
Add Stock Plot Feature to Charting

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1574]
We have a new feature being released in the next 48 hours that plots the orders on the asset price to help visualize fills. 

#### Expected Behavior
Feature including how to activate it is documented.

#### Actual Behavior
Not documented

To activate navigate to the orders tab and click the tiny chart icon next to an order. A new plot will appear with the stock price and the orders for that asset overlayed.

Buy orders appear with a green triangle with sell orders in inverted red triangles. Hovering on the row of the order will highlight the order in the chart.

**Comment by DerekMelchin** [comment]
- https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results#04-Built-in-Charts
- https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results#10-Orders
- https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/results#04-Built-in-Charts
- https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/results#08-Orders
