### ISSUE TITLE
Algorithm's Setting: Custom `TradingDaysPerYear` property 

### ISSUE THREAD

**Issue by Romazes** [QuantConnect/Documentation#1579]
#### Expected Behavior

Currently, the `TradingDaysPerYear` parameter can be set in the algorithm settings. If the user does not set it explicitly, it is expected to be automatically configured based on either the `BrokerageModel` or default to 252.
##### For instance:
```
public override void Initialize()
{
  Settings.TradingDaysPerYear = 200;
}
```
Also, It will be depending from `BrokerageModel`:
- Cryptocurrency Exchanges => 365 days;
- Traditional Stock Exchanges => 252 days;
##### For instance:
```
public override void Initialize()
{
  SetBrokerageModel(BrokerageName.Coinbase, AccountType.Cash);
}
```

#### Actual Behavior

Use hardcoded value `TradingDaysPerYear = 252` for both Cryptocurrency Exchanges and Traditional Stock Exchanges. Unfortunately, Cryptocurrency Exchanges should use **365** days. **It ruins to calculate right statistics of Algorithm.**

#### Related Issue and PR
- [issue](https://github.com/QuantConnect/Lean/issues/7562)
- [PR](https://github.com/QuantConnect/Lean/pull/7690)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by 967f671
