### ISSUE TITLE
Backtest self-categorization

### ISSUE THREAD

**Issue by jhonabreul** [QuantConnect/Documentation#1580]
#### Expected Behavior

We document backtest self-categorization with the new naming and tagging functionalities implemented in https://github.com/QuantConnect/Lean/pull/7683.

Naming:

- We provide the `QCAlgorithm.Name` property which can be set either directly by its setter or with the `SetName` method. Name is limited to 200 characters, so if the value has more characters, it gets truncated.

Tagging:

- Algorithms can now have tags which will be available in the `QCAlgorithm.Tags` property.
- The `Tags` collection can be directly set with the property setter or using the `SetTags` method, which will override any exisiting tags.
- A single tag can be added using the `AddTag` method.
- The collection can hold up to 20 tags.
- As for the name, tags can only have at most 200 characters, or else they will be truncated. Even with the property setter or the `SetTags` method, they will be checked and truncated if necessary.

#### Actual Behavior

New feature, not documented.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by f9e00d6
