### ISSUE TITLE
Expand Chained Options Page with Full Demo

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1582]
#### Expected Behavior
Full demonstration with vol/greeks at bottom of 
https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/universe-selection/options-universes#61-Option-Chained-Universe-Selection

Expand with H3's on Volatility / Pricing Model:
- To override the default [pricing model](https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/options-models/pricing) of the Options, [set a pricing model](https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/options-models/pricing#04-Set-Models) in a security initializer.
- To override the [initial guess of implied volatility](https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/options-models/pricing#03-What-Is-Implied-Volatility3F), set and warm up the underlying [volatility model](https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/options-models/volatility/key-concepts).

#### Actual Behavior
Links to add model pages.

#### Checklist
- [x] I have filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by 7763a6f
See [Options Universes> Example](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/universe-selection/options-universes#99-Example).
