### ISSUE TITLE
Set Asynchronous Flag on Demos

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1584]
We have a new feature that loads universes asynchronously in the background. It increases options and future universes by 30-40%; we should update all the demonstrations to use this flag. as long as the universes aren't using the data they select. e.g. selecting by only data in the selection filter.

https://www.quantconnect.com/docs/v2/writing-algorithms/universes/equity/chained-universes#10-Chain-ETF-and-US-Equity-Options

```
UniverseSettings.Asynchronous = true;
```

**Comment by AlexCatarino** [comment]
Closed by 48a8752
