### ISSUE TITLE
Update Charting/Example to be SMA Cross

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1585]
Using a more classical indicator plot would be more helpful to most people.
https://www.quantconnect.com/docs/v2/writing-algorithms/charting#08-Examples

#### Expected Behavior
Show SMA200 / SMA 50 plot as example not SPY asset pricing.

**Comment by AlexCatarino** [comment]
Closed by c0809e9.
Using two EMA 20 and 50 to cross and plot triangles using the price when they cross.
