### ISSUE TITLE
Delayed Settlement Cash Not Freed for Removed Assets

### ISSUE THREAD

**Issue by jhonabreul** [QuantConnect/Documentation#1603]
#### Expected Behavior

We document the new `GetUnsettledCash` method of the `ISettlementModel` added in https://github.com/QuantConnect/Lean/pull/7727.

This new method allows consumers to detect when there is unsettled cash that hasn't be freed in order to delay security removal.

#### Actual Behavior

New interface property, not documented.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by 173229fc3a28a649144cf4a9f0e084fa041b3089
