### ISSUE TITLE
Name of file to be created is wrong

### ISSUE THREAD

**Issue by Anamaraf** [QuantConnect/Documentation#1607]
https://github.com/QuantConnect/Documentation/blame/84b5dd30a30a6e23d89f1c2ac6d1ce42bfa4b567/06%20LEAN%20Engine/02%20Contributions/02%20Brokerages/02%20Laying%20the%20Foundation/03%20Lay%20the%20Foundation.html#L16

The name of the file to be created must be <brokerageName>BrokerageModel.cs instead of <brokerageName>.cs.

The actual text of the line is:
In the Lean / Common / Brokerages folder, create a <brokerageName>.cs file with a stub implementation that inherits from the DefaultBrokerageModel.

**Comment by AlexCatarino** [comment]
Thank you, @Anamaraf. 
Fixed by: https://github.com/QuantConnect/Documentation/commit/ddfc0b3f5e3ca14b835002980fc1b0aa66762011
