### ISSUE TITLE
SEO image paths need updating for files that have been moved

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1618]
#### Expected Behavior

The github actions validate the image paths in the `metadata.json` files. If they are incorrect, the github action automatically fixes the path for us.

#### Actual Behavior

This isn't implemented yet. When we move files around, it's possible for us to forget to change the image file path in the metadata.json files.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Flagging the error seems easy but automatically fixing is hard - suggest we start with at least alerting us when the image has moved. This would be a simple scan for metadata.json and then validating all the images it contains. Failing the action if they're not all there.

**Comment by AlexCatarino** [comment]
The GitHub Actions don't commit to master, so the script can make the changes and create a new branch:
https://github.com/QuantConnect/Documentation/blob/master/.github/workflows/code_generators.yml#L46
Then we can review the branch before merging.

**Comment by LouisSzeto** [comment]
I think the URL tester is already doing so?

**Comment by LouisSzeto** [comment]
@AlexCatarino now PR #1640 will not erase the indicator reference image links. Maybe this can be closed.
