### ISSUE TITLE
Update IEX Cloud Text

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1620]
Reflect feedback from IEX.

===

From: "To use IEX Cloud, you need an account their Launch, Grow, or Enterprise plan. If you don't have an account, register today and get your API key."

To:

" To use IEX Cloud, you need an account subscribed to one or more [data bundles](https://iexcloud.io/documentation/financial-data/data-bundles.html). You also must select either the Launch, Grow, or Enterprise subscription tier; this dictates your maximum requests per second. If you don’t have an account, [register today](https://iexcloud.io/cloud-login#/register) and get your [API key](https://iexcloud.io/console/tokens). Pricing information can be found [here](https://iexcloud.io/pricing)."

 "Upon registration, your account will automatically start a 7-day free trial. This trial has access to all API endpoints and a rate limit of 5 requests per second. If you have any questions regarding IEX Cloud’s API service, please contact them here: [support@iexcloud.io](mailto:support@iexcloud.io)."

**Comment by AlexCatarino** [comment]
Closed by 50fd9c3
https://www.quantconnect.com/docs/v2/lean-cli/datasets/iex-cloud
