### ISSUE TITLE
Option Indicator Example Algorithms Throw Errors

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1641]
#### Expected Behavior

The example algorithms in https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/gamma#02-Using-G-Indicator run without error.

#### Actual Behavior

```
Runtime Error: 'int' object has no attribute 'Current'
  at OnData
    self.Plot("Gamma" in main.py: line 19
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
This only happened when the greek indicator was updated after the contract expiry.
