### ISSUE TITLE
Standardize tables that show supported orders for brokerages

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1677]
#### Expected Behavior

The tables that show the supported orders for each brokerage ([example](https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/tradier#05-Orders)) show all of the order types.

#### Actual Behavior

They only show the order types that are supported for at least one of the asset classes the brokerage supports.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
Not going to fix this by JB
