### ISSUE TITLE
Custom Data Supports Zipped Files

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1727]
#### Expected Behavior
See https://github.com/QuantConnect/Lean/pull/7976

In [Data Formats](https://www.quantconnect.com/docs/v2/writing-algorithms/importing-data/streaming-data/key-concepts#02-Data-Formats), we mention zipped files. 
In [Set Data Sources](https://www.quantconnect.com/docs/v2/writing-algorithms/importing-data/streaming-data/key-concepts#04-Set-Data-Sources), we add an example of each type

```python

# handles zip files automatically
return SubscriptionDataSource(Bitstamp.KEY, 
    SubscriptionTransportMedium.OBJECT_STORE)

return SubscriptionDataSource("https://cdn.quantconnect.com/uploads/multi_csv_zipped_file.zip",
    SubscriptionTransportMedium.REMOTE_FILE,
    FileFormat.ZIP_ENTRY_NAME)

return SubscriptionDataSource("https://cdn.quantconnect.com/uploads/multi_csv_zipped_file.zip#csv_file_10.csv",
    SubscriptionTransportMedium.REMOTE_FILE,
    FileFormat.ZIP_ENTRY_NAME)
```

#### Actual Behavior
New feature.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/135182ef3acdeacaa04055371b123019db593ac0
