### ISSUE TITLE
Improve URL checker to find Relative Links

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1785]
#### Expected Behavior

We have a github action that ensures all links are absolute links, not relative links.

#### Actual Behavior

Not implemented 

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by eb7653d
