### ISSUE TITLE
Navigation issue/ inconsistency

### ISSUE THREAD

**Issue by nicolad** [QuantConnect/Documentation#1787]
When navigating between nested item and parent there seems to be a routing issue, please check screencast

https://github.com/QuantConnect/Documentation/assets/1477453/ad29c6d9-c387-4350-8656-88b5fe3eed82

**Comment by nicolad** [comment]
long-term IMO a better doc generator might be needed, like


https://docusaurus.io/docs/advanced/routing

**Comment by nicolad** [comment]
@jaredbroad I tried to search through past issues and haven't seen being captured, is this smth that someone is looking into?

**Comment by gaviles** [comment]
Thank you @nicolad, @rjra2611 closing as fixed.
