### ISSUE TITLE
Missing Backtests for Option Strategies 

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1798]
#### Expected Behavior

The following tutorials have an embedded backtest at the bottom so members can reproduce the example
- Long iron condor
- Short iron condor
- Long iron butterfly
- Short iron butterly

#### Actual Behavior

They are missing the backtests

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
fixed
