### ISSUE TITLE
Document New Indicator History API

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1803]
#### Expected Behavior

Document new indicator history APIs at https://github.com/QuantConnect/Lean/pull/8076
#### Actual Behavior

QB.Indicator API are documented but these are tagged as obsolete now

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/6794d941ca75eae8ecbe450c0bb207caa72e1c94
