### ISSUE TITLE
Brokerage Side Orders Handling

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1805]
#### Expected Behavior

- Lean now supports handling brokerage side generated orders, Related PR https://github.com/QuantConnect/Lean/pull/7706. see example https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/CustomBrokerageSideOrderHandlingRegressionAlgorithm.py 
**Currently this is only supported by Terminal Link brokerage** see example looking at terminal link order properties https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_bf05bc5253f076fab4bb81f20537406d.html

#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
We have documented this feature:
https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/brokerage-message-handler
We need to add an H3  e.g.: "Brokerage Support" to inform that it's only supported by Terminal Link.

**Comment by AlexCatarino** [comment]
Closed by f839541eca28e5d496c0dafdfc88d28b8d65f755
