### ISSUE TITLE
Option Strategy Updates

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1819]
#### Expected Behavior

- The [Bear Call Ladder](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/bear-call-ladder) and [Bull Call Ladder](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/bull-call-ladder) pages use the `CallLadder` universe filter.
- The [Bear Put Ladder](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/bear-put-ladder) and [Bull Put Ladder](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/bull-put-ladder) pages use the `PutLadder` universe filter.
- The [Jelly roll](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/jelly-roll#03-Strategy-Payoff) and [Short jelly roll](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/short-jelly-roll#03-Strategy-Payoff) pages have Payoff charts
- All the **Example** sections use their respective Option strategy universe filter.
- The page titles consistently use long/short 
![image](https://github.com/user-attachments/assets/dcdaf027-fab7-4b6f-9b89-98b198fb7b2e)
- > "(By the way, in the QuantConnect Documentation Writing Algorithms BearPutSpread is confused with BullPutSpread and vice versa. The code examples on Git are correct. But that's just a side note.)"
- The subscripts are easy to read 
![image](https://github.com/user-attachments/assets/e7f99a71-ac34-4459-9ca1-a20cc5e73084)

- The text on the Long Iron Butterfly page should be reviewed. ([Strategy Payoff](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/long-iron-butterfly#03-Strategy-Payoff) calls it "long call butterfly" and the [Example](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies/long-iron-butterfly#04-Example) even calls it "short iron butterfly")

---
- Issues with latex:
  - The first 4 should all start with "Market value..."
  - Payoff_T should be Payoff_T1, right?
  - C_0^(T_1) should be C_(T_0)^(T_1), right?
  - There is no point in defining just T because T (with no subscript) is never used
![image](https://github.com/user-attachments/assets/3f4986ce-7211-4701-afe2-e37d47effd17)

#### Actual Behavior

- Undocumented

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
fixed through commit cdfe0862794193ece8c7b0d2421c90341fe73ab1
