### ISSUE TITLE
Empty landing page for CLI API 

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1820]
#### Expected Behavior

This page https://www.quantconnect.com/docs/v2/lean-cli/api-reference is a landing page which shows all of the CLI commands, like our other landing pages ([example](https://www.quantconnect.com/docs/v2/cloud-platform/organizations)).

#### Actual Behavior

The landing page is blank, so we are forced to link to specific API reference pages throughout the docs and if someone clicks the "Documentation" link in the readme, they land on an empty page.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Fixed by 5af197b1ceef50331c2fc31cfd5778655564dd89
