### ISSUE TITLE
Liquidate Api Improvements

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1822]
#### Expected Behavior

- Liquidate API has been improved by normalizing it's behavior with the rest of the trading API returning OrderTickets and accepting async & order properties, see https://github.com/QuantConnect/Lean/pull/8210
#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/41a2a6940b15d80a6fd81d189350f1dc9545b15b

**Comment by AlexCatarino** [comment]
Closed by d63afc5092f478571394587c4a2eaa8ed25ca7ee
