### ISSUE TITLE
Refactor: Coinbase documentation

### ISSUE THREAD

**Issue by Romazes** [QuantConnect/Documentation#1837]
#### Expected Behavior

- The authentication process should work smoothly with the updated key properties.
- Users should be informed of the correct format when providing the private key.

#### Actual Behavior

- The authentication process has been updated, but users may not be aware of the necessary changes.
- The key properties have been renamed:
  - `API key` is now `Api Name`
  - `API secret` is now `Api Private Key`
- When users pass the private key in the format:
```
-----BEGIN EC PRIVATE KEY-----\nxxx\nxxx\nxxx\n-----END EC PRIVATE KEY-----\n
```
they must:
- Remove the `BEGIN` and `END` lines.
- Remove all `\n` characters.
- Format the private key as `xxx xxx xxx`.

#### Additional Resources
We are using new [CDP API keys](https://docs.cdp.coinbase.com/advanced-trade/docs/getting-started/)

![image](https://github.com/user-attachments/assets/00762832-425e-4cb3-b245-ea415486768f)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed. See [Coinbase > Account Types](https://www.quantconnect.com/docs/v2/cloud-platform/live-trading/brokerages/coinbase#02-Account-Types).
