### ISSUE TITLE
Table for DataNomarlizationMode not being displayed for Python.

### ISSUE THREAD

**Issue by baobach** [QuantConnect/Documentation#1857]
#### Expected Behavior

Table should be displayed with all the available Normalization mode for both Python and C# snippets.
[Table Link](https://www.quantconnect.com/docs/v2/research-environment/datasets/us-equity#07-Data-Normalization)

#### Actual Behavior

Table available for C# but not for Python

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Thank you for the report! Fixed by [#d069802](https://github.com/QuantConnect/Documentation/commit/d069802412abb6f764a736aa3a23b285eaf2f556).
