### ISSUE TITLE
Examples Issue: Securities / US Equities / Data Preparation

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#1864]
#### Examples

 - Example 1: Use Market on open orders 
 - Example 2: Demonstrate pinning the opening auction price tick; 
 - https://www.quantconnect.com/terminal/processCache/?request=embedded_backtest_8025decf2aae4b0ba9653324a61256c6.html

### Remember
 - Don't use variables that aren't defined.
 - Comment every line or few lines.
 - Include 40-100 word explanation. 
 - Declare everything you need each example. 
 - Copy from IDE to Docs so confirm it works. Copy-pastable examples.
 - ALWAYS make Examples.html at the end.

**Comment by jaredbroad** [comment]
@baobach will be assisting with this one @LouisSzeto can leave it for him

**Comment by baobach** [comment]
I'll take this one
