### ISSUE TITLE
Documentation for generic live command support

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Documentation#1915]
#### Expected Behavior

- Documentation for new generic live command support.  See https://github.com/QuantConnect/Lean/pull/8330 & https://github.com/QuantConnect/lean-cli/pull/501
#### Actual Behavior

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
See https://github.com/QuantConnect/Lean/pull/8348, adding Link support

**Comment by AlexCatarino** [comment]
See [Live Trading > Commands](https://www.quantconnect.com/docs/v2/writing-algorithms/live-trading/commands).
