### ISSUE TITLE
Outdated Example for Multi-Alpha Algorithms

### ISSUE THREAD

**Issue by efJerryYang** [QuantConnect/Documentation#1924]
#### Expected Behavior

The code example for Multi-Alpha Algorithms needs to be corrected for both C# and Python.

We need to use the `Algorithm.Insights.GetActiveInsights(Algorithm.UtcTime).ToList();` to achieve this. I am not sure if we should validate the insights first (as in the default `GetTargetInsights` implementation).

See the lean repository [PortfolioConstructionModel.cs#L164C1-L177C10](https://github.com/QuantConnect/Lean/blob/809faa24dea8c186b0a11dec4707ea0c9f2d216e/Algorithm/Portfolio/PortfolioConstructionModel.cs#L164C1-L177C10).

#### Actual Behavior

The code example for Multi-Alpha Algorithms seems to be outdated for both C# and Python. The Documentation: [04-Multi-Alpha-Algorithms](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/portfolio-construction/key-concepts#04-Multi-Alpha-Algorithms).

The property `InsightsCollection` does not exist in the `PortfolioConstructionModel.cs` at the master branch and therefore we can not invoke `InsightCollection.GetActiveInsights(Algorithm.UtcTime).ToList();` to get the insights for multiple alphas.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Thank you for the report, @efJerryYang!
Fixed by [#7da6206](https://github.com/QuantConnect/Documentation/commit/7da62062c0c53d04f1c19f06b8d3563b07b293ec).
