### ISSUE TITLE
Outdated: Nasdaq Data Link

### ISSUE THREAD

**Issue by Romazes** [QuantConnect/Documentation#1944]
#### Expected Behavior

- Modify old existing examples to new ones.
- Describe property `new SubscriptionDataSource(...) { Sort = true }` when users want to use their `custom data classes`.

#### Actual Behavior

We can see old examples which Nasdaq has not supported already.

#### Related PR
- https://github.com/QuantConnect/Lean/pull/8352
- https://github.com/QuantConnect/Lean.DataSource.NasdaqDataLink/pull/13

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed. See [Unsorted Data](https://www.quantconnect.com/docs/v2/writing-algorithms/importing-data/streaming-data/key-concepts#06-Unsorted-Data)
