### ISSUE TITLE
FilteredIdentity non functioning example

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Documentation#1951]
#### Expected Behavior
documentation of FilteredIdentity c# example should be functioning on qc cloud (i think)

#### Actual Behavior
it is not

#### Potential Solution
construct a valid c# expression for the filter parameter

#### Reproducing the Problem
go to https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/filtered-identity
copy code to qc cloud
see eror

#### System Information
qc cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Hi @superichmann,
If you see an issue with the Docs, please report here:
https://github.com/QuantConnect/Documentation/issues
