### ISSUE TITLE
Last day in historical data request?

### ISSUE THREAD

**Issue by realcake** [QuantConnect/Documentation#2]
If I get the last seven minute resolution trade bars...
```
IEnumerable<TradeBar> bars = History("SPY", 14, Resolution.Minute);
List<TradeBar> list = bars.ToList();
```

I keep forgetting if the first or last element in the list would be the most recent TradeBar. 
It would be nice if it was added to the docs page.

**Comment by jaredbroad** [comment]
Welcome to the new documentation!!! :D Thanks we'll add that section shortly.
