### ISSUE TITLE
Handling data - checking for contents of `Slice data` object.

### ISSUE THREAD

**Issue by Doggie52** [QuantConnect/Documentation#204]
Hi,

Seeing more and more posts on the forums where people are getting errors because they are trying to access parts of the `data` object that do not exist.

The section on _Handling Data_ contains a lot of examples, but only some of them perform any content checking. They should be upgraded to do so.

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/us-equity/handling-data)
