### ISSUE TITLE
Clarify different approaches in Consolidating Data - Consolidators Indicators section

### ISSUE THREAD

**Issue by xinweimetrics** [QuantConnect/Documentation#224]
The code snippets are not entirely clear in demonstrating the approaches laid out in the paragraphs. We'd better modify the code for the demonstration purpose.

_Documentation URL: https://www.quantconnect.com/docs/algorithm-reference/consolidating-data#Consolidating-Data-Consolidators--Indicators_

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/consolidating-data/updating-indicators#03-Custom-Indicator-Periods).
