### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by globophobe** [QuantConnect/Documentation#229]
I prefer docs offline. It would be really great if the docs were in Markdown, so they would be easy to search with grep or ripgrep.

**Comment by DerekMelchin** [comment]
We decided to write the docs in html/php. In the future, we can work on an offline alternative (generate the docs in PDF) so that you can use the search tools of any PDF reader. Subscribe to https://github.com/QuantConnect/Documentation/issues/379 to track the feature progress.
