### ISSUE TITLE
Add Order For Option Trading in Trading and Order Section

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#245]
The following order types are not covered by docs:
- `ExerciseOption` method that is used to exercise options.
- `Order(OptionStrategy strategy, int quantity)` method that is used to place option strategy order.

**Comment by DerekMelchin** [comment]
Fixed in docs v2 [here](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-types/option-exercise-orders) and [here](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/option-strategies).
