### ISSUE TITLE
Adds Future and Option Universe Selection 

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#265]
`FutureUniverseSelection` and `OptionsUniverseSelection` are not included in [Algorithm Framework - Universe Selection](https://www.quantconnect.com/docs/algorithm-framework/universe-selection) documentation.

**Comment by DerekMelchin** [comment]
Fixed in docs v2 [here](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/universe-selection/futures-universes) and [here](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/universe-selection/options-universes).
