### ISSUE TITLE
Add Information about Bitfinex Brokerage Model

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#266]
Missing information about Bitfinex in the [Brokerage Supported Order Types](https://www.quantconnect.com/docs/algorithm-reference/reality-modelling#Reality-Modelling-Brokerage-Supported-Order-Types) table.

**Comment by DerekMelchin** [comment]
Added in docs v2.
https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/brokerages/bitfinex#05-Orders
