### ISSUE TITLE
Updates List of Supported Crypto-Currency Pairs for Coinbase Pro

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#267]
The following section is out-of-date: [Coinbase Pro Exchange](https://www.quantconnect.com/docs/data-library/crypto#Crypto-Coinbase-Pro-Exchange)
since new pairs were added by https://github.com/QuantConnect/Lean/pull/3341/

**Comment by DerekMelchin** [comment]
Solved in [Coinbase Pro dataset listing](https://www.quantconnect.com/datasets/coinbase-pro-crypto-price-data).
