### ISSUE TITLE
Refresh LEAN API Documentation

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#283]
LEAN Documentation on qc.com is old

**Comment by omidkrad** [comment]
Need to update: In [Features and Abilities](https://www.quantconnect.com/lean/documentation/topic3.html) it says Lean is based on [IranPython](https://ironpython.net), but now it's based on [PythonNet](https://pythonnet.github.io).

**Comment by AlexCatarino** [comment]
LEAN Documentation can be found on:
- https://www.lean.io/docs/v2/lean-engine/class-reference/index.html

Generated by [QuantConnect/Lean.Reference](https://github.com/QuantConnect/Lean.Reference/)
