### ISSUE TITLE
Explicitly Say that RollingWindow Only Accepts native and C# Types

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#303]
We can read in the docs:
> We can store any type of object in a RollingWindow, since it is a generic type with a given max length ([source](https://github.com/QuantConnect/Documentation/blob/master/02%20Algorithm%20Reference/10%20Rolling%20Window/01%20Introduction.html#L11))
which is not true for Python types, for example:
```python
self.closeWindow = RollingWindow[tuple](4)
```
is not allowed.

**Comment by jaredbroad** [comment]
We should support it somehow :) maybe needs a wrapper.

**Comment by DerekMelchin** [comment]
Closing because it's a lean issue
