### ISSUE TITLE
Intrinio Economic Series Data link is broken

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Documentation#304]
02 Algorithm Reference/04 Importing Custom Data/05 Intrinio Custom Data.html
Broken link: https://docs.intrinio.com/master/economic-indices#home

**Comment by DerekMelchin** [comment]
Solved in docs v2. Intrinio is no longer used.

https://www.quantconnect.com/docs/v2/research-environment/tutorials/requesting-historical-data/custom-data
