### ISSUE TITLE
Add a Section in Algorithm Framework to Explain the Separation of Concerns Principle

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#307]
FAQ: users want to add/remove securities and/or insights when the risk model emits a zero-quantity portfolio target and, consequently, the position is closed by the execution model.
We should add a section on the Separation of Concerns principle to state that models should not communicate and the universe and insights should be the same across different choices of PCM, RMM and EM.

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/overview#06-Separation-of-Concerns)
