### ISSUE TITLE
Add Section in Scheduled Events Explaining Incompatibility With Daily/Hour Data

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#308]
Algorithms that subscribe to low-resolution data (daily, but also hour) and implement scheduled events are not recommended because there is not data point with a timestamp that matches the scheduled event time (or that is reasonably close).
https://github.com/QuantConnect/Lean/issues/3687 point to a solution, but a more comprehensive explanation could be added to the docs.

**Comment by jaredbroad** [comment]
I don't know if documenting this is the right solution -- I think we need to simply disallow it as its too easy to miss the error message.
