### ISSUE TITLE
All support brokerage enums aren't listed

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Documentation#310]
https://github.com/QuantConnect/Documentation/blob/master/02%20Algorithm%20Reference/02%20Initializing%20Algorithms/07%20Cash%20and%20Brokerage%20Models.html

https://www.quantconnect.com/docs/algorithm-reference/initializing-algorithms#Initializing-Algorithms-Cash-and-Brokerage-Models

In [Reality Modelling](https://www.quantconnect.com/docs/algorithm-reference/reality-modelling#Reality-Modelling-Brokerage-Models), the most recent model, e.g. Alpaca is not listed.

**Comment by DerekMelchin** [comment]
Fixed in docs v2. Each brokerage user guide shows the brokerage enum. For example:
https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/brokerages/atreyu#02-Account-Types
