### ISSUE TITLE
Update Machine Learning Training Limits for New Organization Nodes.

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#346]
The new values are:

case 'B-MICRO': SetTrainingLimits($controls, 20, 1, 1440);
case 'B2-8': SetTrainingLimits($controls, 30, 5, 1440);
case 'B4-12': SetTrainingLimits($controls, 60, 10, 1440);
case 'B8-16': SetTrainingLimits($controls, 90, 15, 1440);

case 'L-MICRO': SetTrainingLimits($controls, 30, 5, 1440);
case 'L1-1': SetTrainingLimits($controls, 60, 10, 1440);
case 'L1-2': SetTrainingLimits($controls, 90, 15, 1440);
case 'L1-4': SetTrainingLimits($controls, 120, 20, 1440);

**Comment by DerekMelchin** [comment]
Closing because of #563 
The content is available in docs v2 [here](https://www.quantconnect.com/docs/v2/our-platform/user-guides/organizations/resources#04-Resource-Limits)
