### ISSUE TITLE
Add CoarseFundamental.Price and Clarify History Method Data Normalization

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#363]
(1) The [docs](https://www.quantconnect.com/docs/algorithm-reference/universes#Universes-Coarse-Universe-Selection) should state that the CoarseFundamental class has a Price member. It should be clear that this member is raw price, not adjusted.

(2) The docs should specify that the normalization of the data returned from a History request matches the normalization of the data subscription. 

See [this related thread](https://www.quantconnect.com/forum/discussion/2604/using-datanormalizationmode-raw-and-history/p1).

**Comment by jpangburn** [comment]
It's not obvious from the documentation, but `CoarseFundamental` extends from a base class named `BaseData`.  At the bottom of the universes doc at [Custom Universe Selection](https://www.quantconnect.com/docs/algorithm-reference/universes#Universes-Custom-Universe-Selection) there's a clickable `BaseData` class.  It lists the `Price` member along with `Symbol` and some other potentially useful members.

I had run into the same problem, and went to go fix the documentation myself.  But these expandable sections are auto generated from comments in the actual classes, so I couldn't see how to make them include the members from the super class.  Maybe I'll add a "see also `BaseData` superclass" to the doc where CoarseFundamental shows up?  But it seems like a better fix is for the documentation auto generator to let you see superclass members.  I have no idea how to help with that.

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/historical-data/history-requests#04-Request-Data)
