### ISSUE TITLE
Fixes Broken Link in Research on Indicators - Introduction

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#364]
Link to Reference Table in [Research on Indicators - Introduction](https://www.quantconnect.com/docs/research-2/research-on-indicators#Research-on-Indicators-Introduction) is broken since it has the wrong link. Should be: 
https://www.quantconnect.com/docs/algorithm-reference/indicators#Indicators-Reference-Table

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/key-concepts#01-Introduction)
