### ISSUE TITLE
Adds Section to Research About API

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#367]
https://github.com/QuantConnect/Lean/pull/4898
https://github.com/QuantConnect/Lean/blob/master/Research/KitchenSinkQuantBookTemplate.ipynb

**Comment by DerekMelchin** [comment]
Added in docs v2. Here is a link to **[QuantConnect API > Projects](https://www.quantconnect.com/docs/v2/research-environment/tutorials/quantconnect-api/projects)**.
