### ISSUE TITLE
MorningStar Group and Industry Codes not updated

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Documentation#373]
[Docs](https://www.quantconnect.com/docs/data-library/fundamentals#Fundamentals-Asset-Classification) with missing/outdated info.

[Thread](https://www.quantconnect.com/forum/discussion/9866/morningstar-group-amp-industry-codes-documentation-needs-updated/p1)

Backtest 1 (Group Codes: 20610 shows up in backtest but not in docs): https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_36219cc09e2c85733e0a512898416e63.html

Backtest 2 (Industry Codes: 20610010 shows up in backtest but not in docs): https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_150a5ae06a29399059294878ff66fb37.html

**Comment by LouisSzeto** [comment]
Inclusive in:
https://github.com/QuantConnect/Lean/blob/5d762d16b2ec7bd48fd766b772b0921862deda22/Common/Data/Fundamental/AssetClassificationHelper.cs

Added to docs and dataset listing page by code generator https://github.com/QuantConnect/Documentation/blob/master/fundamentals-table-code-generator.py
