### ISSUE TITLE
Clarify Indicator Extensions and Add Examples

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#378]
Clarify these two cases:

- Unlike all of the other IndicatorExtensions, Of requires an unregistered indicator. The code example is kind of insufficient to understand this. Actually in general, the class names and constructor arguments you’d use to create an unregistered indicator don’t show up in the main docs, we have to look them up in the reference docs.
- The document seems to show the arguments in the reverse of their actual order from looking at the reference doc in Python. This is because of extension methods use of `this` as the first parameter that doesn't translate well in Python.

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/combining-indicators).
