### ISSUE TITLE
Show How to Use The Web IDE to Place Orders in Live Trading

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#380]
Explains that Lean does not synchronize the positions while the algorithm is running.
Ref.: https://www.quantconnect.com/forum/discussion/10612/self-portfolio-quot-spy-quot-invested-when-is-updated

**Comment by DerekMelchin** [comment]
> Show How to Use The Web IDE to Place Orders in Live Trading

Added in docs v2 [here](https://www.quantconnect.com/docs/v2/our-platform/tutorials/live-trading/brokerages/interactive-brokers#06-Place-Manual-Orders).

> Explains that Lean does not synchronize the positions while the algorithm is running

Added in docs v2 [here](https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/brokerages/interactive-brokers#14-Deposits-and-Withdraws).
