### ISSUE TITLE
Invalid field fine.OperationRatios.ROE.OneMonth

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Documentation#381]
[Docs](https://www.quantconnect.com/docs/data-library/fundamentals)
[Relevant Thread](https://www.quantconnect.com/forum/discussion/10786/operationratios-roe/p1)

**Comment by DerekMelchin** [comment]
Solved in [US Fundamentals dataset listing](https://www.quantconnect.com/datasets/morning-star-us-fundamentals).

![image](https://user-images.githubusercontent.com/38889814/153513537-00f5989a-d023-4379-8513-3f88c6fa1fea.png)
