### ISSUE TITLE
Live Documentation Questions

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Documentation#387]
* How can I test having my strategy in a state where there are open trades and I’ve stopped/restarting it?

* When is data available from the broker? I was originally doing my initialization in the init method but was informed the actual data isn’t available until after the warmup’s finished.

* How to run with paper trading?

**Comment by AlexCatarino** [comment]
- Can I deploy 2 different algorithms to the same server?
- How can I tell which algorithm is running on which server?

**Comment by DerekMelchin** [comment]
> How can I test having my strategy in a state where there are open trades and I’ve stopped/restarting it?

Added in docs v2 [here](https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/deployment#05-Wizard).


> When is data available from the broker? I was originally doing my initialization in the init method but was informed the actual data isn’t available until after the warmup’s finished.

Added in docs v2 [here ](https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/data-feeds/brokerage-data-feeds)and [here](https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/data-feeds/brokerage-data-feeds/interactive-brokers).


> How to run with paper trading?

Added in docs v2 [here](https://www.quantconnect.com/docs/v2/our-platform/tutorials/live-trading/brokerages/quantconnect-paper-trading).


> Can I deploy 2 different algorithms to the same server?

Added in docs v2 as the first sentence [here](https://www.quantconnect.com/docs/v2/our-platform/tutorials/live-trading/brokerages/interactive-brokers#04-Deploy-Live-Algorithms).


> How can I tell which algorithm is running on which server?

Added in docs v2 [here](https://www.quantconnect.com/docs/v2/our-platform/tutorials/projects/working-with-the-ide#06-View-Available-Nodes).
