### ISSUE TITLE
Screencap snippets out of data for 'fundamental-data' document

### ISSUE THREAD

**Issue by cauldnz** [QuantConnect/Documentation#395]
The '03_using_fundamental_data.html' document has out of data screenshots.
The example code in the document includes AAL whereas the screenshots do not.

Given that the narrative in the document is closely tied to the screenshots I suggest it's worth recapturing the screenshots.

**Comment by DerekMelchin** [comment]
Solved in docs v2
![image](https://user-images.githubusercontent.com/38889814/153513351-50f40da2-b138-40c9-8ade-ff2504d78a80.png)
https://www.quantconnect.com/docs/v2/research-environment/tutorials/accessing-fundamenal-data#05-Plot-Data
