### ISSUE TITLE
Add Information About Data Bundles From Interactive Broker

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#398]
It's a common member request. "Which market data should I subscribe to?"
https://www.interactivebrokers.com/en/index.php?f=14193
- US Equity and Options Add-On Streaming Bundle: US Equity Options
- US Securities Snapshot and Futures Value Bundle: US Futures (not VIX)
- CFE Enhanced Top of the Book (L1): VIX Futures

**Comment by DerekMelchin** [comment]
Solved in docs v2
https://www.quantconnect.com/docs/v2/our-platform/user-guides/live-trading/data-feeds/brokerage-data-feeds/interactive-brokers#07-Pricing
