### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by Swopper050** [QuantConnect/Documentation#399]
Clicking on the GitHub sign at the bottom of the page `Contribute to the documentation: <sign>` redirects me to
```
https://github.com/QuantConnect/Documentation/tree/master/00%20Home%2F01%20Home
```
which yields an 404 error.

I am using a Mac with Firefox.

**Comment by DerekMelchin** [comment]
Solved in docs v2
![doc-to-github-demo](https://user-images.githubusercontent.com/38889814/153513790-4125b00a-2139-451e-820f-193f86415c67.gif)

https://www.quantconnect.com/docs/v2/research-environment/tutorials/accessing-fundamenal-data#05-Plot-Data
