### ISSUE TITLE
Possible typo's in the trading and orders page

### ISSUE THREAD

**Issue by Swopper050** [QuantConnect/Documentation#400]
1. Maybe I am misreading the section, but shouldn't the underlined text say 'stop market order'?

![Screenshot 2021-07-04 at 08 43 18](https://user-images.githubusercontent.com/38559175/124375731-f8fc5b00-dca3-11eb-9de5-55274358cfa2.png)

2. Prce --> Price

![Screenshot 2021-07-04 at 08 45 27](https://user-images.githubusercontent.com/38559175/124375801-45e03180-dca4-11eb-907a-21a94061bcee.png)

**Comment by DerekMelchin** [comment]
Fixed in docs v2 [here](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-types) and [here](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/order-management/order-tickets#04-Update-Orders)
