### ISSUE TITLE
Incomplete display on long crypto symbols

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Documentation#401]
Crypto symbols with longer than 6 characters cannot be correctly displayed in the documentation.

[docs' symbol list](https://www.quantconnect.com/docs/data-library/crypto#Crypto-Bitfinex) (Crypto-Bitfinex)

[correct symbol list](https://github.com/QuantConnect/Lean/blob/e453635458b32c3842fd0362dc504646e9a54f0c/Data/symbol-properties/symbol-properties-database.csv) (from line 470-764)

**Comment by DerekMelchin** [comment]
Closing because this is now fixed in the [Bitfinex dataset listing](https://www.quantconnect.com/datasets/bitfinex-crypto-price-data).
![image](https://user-images.githubusercontent.com/38889814/153499519-c0d93f2b-340f-4291-950c-66fecb9764a4.png)
