### ISSUE TITLE
Indicators Database is Out of Date

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#402]
https://cdn.quantconnect.com/docs/indicators.json
E.g.: does not include SchaffTrendCycle (STC)
https://www.quantconnect.com/forum/discussion/11885/indicator-schafftrendcycle/p1

**Comment by DerekMelchin** [comment]
Added in docs v2 [here](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/indicator-reference/schaff-trend-cycle)
