### ISSUE TITLE
Document the event ordering, and what should be done in each event

### ISSUE THREAD

**Issue by DavidThielen** [QuantConnect/Documentation#520]
An item that would be incredibly valuable for the documentation

They did this with Windows early on and it was a gigantic help (disclaimer, I was a senior developer on the Windows team at Microsoft). It was a listing of the events an app normally got, and the order they fired. That ordering, which in places depended on what was happening, helped developers a lot. By seeing the sequence it was a lot easier for them to figure the best place for each set of their code.

And it listed what should be done in each. It was amazing all the wrong events programmers painted the screen in. Including Microsoft developers writing Windows widgets.

And for QC, you would need it both when using the Algorithm Framework and for those that do not use the framework.

**Comment by DerekMelchin** [comment]
https://www.quantconnect.com/docs/v2/writing-algorithms/key-concepts/algorithm-engine#05-Event-Flow
