### ISSUE TITLE
Update custom data bitcoin documentation to not use obsolete members

### ISSUE THREAD

**Issue by mchandschuh** [QuantConnect/Documentation#56]
A user grabbed the following code from the documentation [here](https://www.quantconnect.com/lean/documentation/topic16.html).

This example references the obsolete methods using `DataFeedEndpoint` instead of using the `isLiveMode` overload. Also, we should consider adding a section in the documentation to describe subclassing from `TradeBar` so custom data works as expected with consolidators.

See: https://github.com/QuantConnect/Lean/issues/1903

**Comment by DerekMelchin** [comment]
Closing because https://www.quantconnect.com/lean/documentation/ is now a dead link. The docs are now at https://www.quantconnect.com/docs/v2/
