### ISSUE TITLE
Heikin Ashi Indicator

### ISSUE THREAD

**Issue by michaelsrew** [QuantConnect/Documentation#59]
is missing in the documentation.
I see only HullMovingAverage

**Comment by michaelsrew** [comment]
Hmm docu lists 62 indicators.
i counted 71 in the repository.....

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/indicator-reference/heikin-ashi)
