### ISSUE TITLE
New code example backtest showing how to prevent the future from ever being known

### ISSUE THREAD

**Issue by garyha** [QuantConnect/Documentation#65]
The default on QuantConnect is for the future to be injected into backtesting. Adjusted prices. Sounds nice. And is devastating.

This is a request for a new example backtest to be posted in documentation, one that will show users a complete solution on how to insure the future does not (**cannot**) influence backtesting. Such an example should benefit QuantConnect, it should greatly improve chances of success for both business and users.

Please see https://www.quantconnect.com/forum/discussion/3806/security-object-shows-067-history-shows-12/p1

**Comment by jaredbroad** [comment]
Welcome @garyha ! Thanks for the interest in LEAN -- requesting raw pricing in backtests is well documented; 
https://www.quantconnect.com/bootcamp/#task-17/Set-Data-Normalization-Mode
https://www.quantconnect.com/docs/algorithm-reference/initializing-algorithms#Initializing-Algorithms-Selecting-Asset-Data

Closing issue but welcome future suggestions!
