### ISSUE TITLE
Github respository link in the community forum 

### ISSUE THREAD

**Issue by michaelsrew** [QuantConnect/Documentation#66]
Please add the github respository link with the sample algos(C# & pyhton) below the "We're Hiring" part. 
a lot of people doesnt know that you hide a lot of good examples somewhere.

trying implementing dropbox access:
https://www.quantconnect.com/forum/discussion/1842/is-it-possible-to-use-http-to-fetch-json-data-on-scheduler/p1/comment-11606

also a guy searching for a good rolling window example in python lately.

**Comment by jaredbroad** [comment]
@michaelsrew we tried to put them inline with every section of the documentation at the top of the pages ("Demonstration Algorithms"). Do you think a link to the whole list would help?

**Comment by michaelsrew** [comment]
definitely yes.
maybe you could count clicks on that link inside of the webserver logs. i dont know if you want to do that or play around and delete it if does not work but people are asking for simple algos that you already have!
+ the docu does not has a list of all algos. Its like an explosion of stuff you have to put together when you need something (the docu).
In books you have at the back an index with letters indexing words addressed in chapters to see where it get used. 
where is QC index :D
![grafik](https://user-images.githubusercontent.com/22957504/39754015-0fcf0cb2-52c1-11e8-9dc2-fb624ffbf3ef.png)

also i would check if someone clicks on this TAGS in the logs if you have the possibility.

you have a docu yes but also add the index if you have it. 
you could create a poll instead the data issues tab to ask people directly for needed stuff.
or ask them there with only a question if this github link is usefull to get directly answers not asking me :)

**Comment by michaelsrew** [comment]
also for people that dont read documentation before they turn on a device :)

**Comment by michaelsrew** [comment]
https://www.quantconnect.com/forum/discussion/3813/indicator-rolling-window-to-get-indicator-values-n-days-back/p1/comment-11647

**Comment by michaelsrew** [comment]
https://www.quantconnect.com/forum/discussion/3816/feeding-historical-data-to-consolidators/p1/comment-11646

**Comment by jaredbroad** [comment]
Thanks @michaelsrew lets see if it helps

![image](https://user-images.githubusercontent.com/2243225/39867235-f1287584-5421-11e8-86a4-4d59d58b8441.png)

**Comment by michaelsrew** [comment]
nice,....thanks for giving it a try
yes hopfully it helps :)
