### ISSUE TITLE
use python 3.8x

### ISSUE THREAD

**Issue by oldmangreg** [QuantConnect/Documentation#675]
Would suggest adding note that as of this time only python 3.8 is supported.

My default python is 3.10x and I created a virtual env and did a `pip install --upgrade lean` then tried `lean login` which failed with an error like  `[Errno 2] No such file or directory: 'C:\\Users\\<myuser>\\.lean\\credentials'`

I then deleted this env and created a python 3.8x virtual env and ran the same which worked.

Thanks,
Greg

**Comment by DerekMelchin** [comment]
Added in [docs v2](https://www.quantconnect.com/docs/v2/lean-cli/installation/installing-pip#01-Introduction).
