### ISSUE TITLE
Common errors chapter

### ISSUE THREAD

**Issue by michaelsrew** [QuantConnect/Documentation#71]
working with data some people are starting to write an algo but than get some errors they dont unterstand.
You have it sometimes in c# than little bit better in python.
than its sometimes missing:

if (not self._rc.IsReady) or (not data.ContainsKey(self._spy)): return
 if data[self._spy] is None: return

equivalent in c#:
if (!data.ContainsKey("SPY")) return;
:(

so it depends on the algo you are looking at if you have problems or not !

that is why an common errors section is missing:
https://www.quantconnect.com/forum/discussion/3930/problem-with-launching-while-backtesting

System.NullReferenceException

even if that was not the problem it is sometimes a common problem for developers to rely on the data with holes from the data provider.

**Comment by DerekMelchin** [comment]
Fixed in [docs v2](https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/us-equity/handling-data)
