### ISSUE TITLE
Adds Classic Renko Consolidator Documentation

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#855]
No documentation for ClassicRenkoConsolidator on
https://www.quantconnect.com/docs/v2/writing-algorithms/consolidating-data/consolidator-types

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
Added here
https://www.quantconnect.com/docs/v2/writing-algorithms/consolidating-data/consolidator-types#05-Renko-Consolidators
