### ISSUE TITLE
Missing alt tags on images

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#928]
#### Expected Behavior

All non-decorative images have an `alt` description that follows [the style guide](https://docs.rackspace.com/docs/style-guide/screenshots/image-guidelines#image-checklist).

#### Actual Behavior

Missing alt tags

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by LouisSzeto** [comment]
Reopening since not of them have been done
