### ISSUE TITLE
Inconsistent Python data type hints

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#929]
#### Expected Behavior

The Python data type hints are consistent.

#### Actual Behavior

We use `list` and `List` throughout the docs. This should be standardized.
See [the Python docs](https://docs.python.org/3/library/typing.html) and the last example [here](https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/universe-selection/scheduled-universes).

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
We should use capital `List` accoring to PEP0484:
https://peps.python.org/pep-0484/
