### ISSUE TITLE
Incorrect "ID" abbreviation

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#931]
#### Expected Behavior

We abbreviate as "ID" and "IDs", as per the [style guide](https://docs.rackspace.com/docs/style-guide/style/abbreviations).

#### Actual Behavior

We abbreviate as "id" in many cases. Some of these are imported from LEAN code.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Assigned @LouisSzeto because "imported from LEAN" means the code generator should handle it.
The code generator should dump a file with the occurrences, so we can fix them in Lean too.

**Comment by LouisSzeto** [comment]
Tagging `backlog` since the rest of the fix will be on LEAN and Lean-CLI repo
