### ISSUE TITLE
API Reference missing content

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#934]
#### Expected Behavior

We have a **Cloud Platform > API Reference** and **Research Environment > QuantConnect API** section for all the methods/endpoints in the API

#### Actual Behavior

We are missing some methods from https://www.lean.io/docs/v2/lean-engine/class-reference/classQuantConnect_1_1Api_1_1Api.html

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
![image](https://user-images.githubusercontent.com/38889814/215583147-51b219f5-aeda-4dab-a714-a594448b921c.png)
![image](https://user-images.githubusercontent.com/38889814/215583163-06eab60d-e97f-4d3a-8e3b-c6851c1b56cd.png)

**Comment by DerekMelchin** [comment]
We'll need to update the links on 
- [Downloading Data - Documentation QuantConnect.com](https://www.quantconnect.com/docs/v2/cloud-platform/api-reference/downloading-data/)
- [Reports - Documentation QuantConnect.com](https://www.quantconnect.com/docs/v2/cloud-platform/api-reference/reports/)

so that they point to the Research Environment API pages

**Comment by AlexCatarino** [comment]
We have opted to only document the relevant endpoints: [Research Environment > Meta Analysis](https://www.quantconnect.com/docs/v2/research-environment/meta-analysis/key-concepts)

**Comment by jaredbroad** [comment]
Closing as should separate the cloud API from the LEAN API reference docs.
