### ISSUE TITLE
No explanation of how to filter weekly option contracts

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#936]
#### Expected Behavior

In [Create Subscriptions](https://www.quantconnect.com/docs/v2/writing-algorithms/securities/asset-classes/index-options/requesting-data#02-Create-Subscriptions), we explain how to filter the symbols from `GetOptionContractList` based on if they are weekly or not.
```
OptionSymbol.IsStandard(symbol)
OptionSymbol.IsWeekly(symbol)
```

#### Actual Behavior

We don't currently explain this. Waiting on https://github.com/QuantConnect/Lean/issues/6872

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/commit/8748ab5bc5464a77a5a33b47c199128550455eeb
