### ISSUE TITLE
Missing docs on mixing universes

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#942]
#### Expected Behavior

We have a **Writing Algorithms > Universes > Combining Universes** page that explains how to mix the various types of universes. For example, [Coarse + Scheduled universe](https://www.quantconnect.com/forum/discussion/14418/is-it-possible-to-reset-a-universe-at-a-specific-time/p1), [ETF + Coarse](https://www.quantconnect.com/forum/discussion/14690/etf-constituent-universe-with-coarse-selector/p1), Crypto + Scheduled, or Alt Data + Scheduled.
- To run ETF constituents and then coarse universe, we can just save the list of symbols in the ETF filter function.
- [Related lean issue](https://github.com/QuantConnect/Lean/issues/6848)

The page should discuss Live Trading Considerations, because will it always work in live mode if data doesn't arrive at the same time?

#### Actual Behavior

We don't explain these techniques yet.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by levijosman** [comment]
class TopGainersUniverseSelectionModel(FundamentalUniverseSelectionModel):
    def __init__(self, Period=1, filterFineData=False, universeSettings=None, universeCount=10):
        super().__init__(filterFineData, universeSettings)
        self.universeCount = universeCount
        self.stateData = {}
        self.spy_constituents = []

    def SelectCoarse(self, algorithm, coarse):
        # Retrieve SPY constituents
        self.Universe.ETF("SPY", Market.USA, self.UniverseSettings, spy_constituents)
        # Only analyze equities that are constituents of the SPY ETF
        spy_constituents = lambda constituents: [x.Symbol for x in constituents]

        for c in spy_constituents:
            if c.Symbol not in self.stateData:
                self.stateData[c.Symbol] = self.SelectionData(c.Symbol, 1)

            avg = self.stateData[c.Symbol]
            avg.update(c.EndTime, c.Price, c.Volume)

        values = [x for x in self.stateData.values() if x.volume > 100000.............

What am I doing wrong? Could you provide a Python example or missing docs please?

**Comment by levijosman** [comment]
`class CoarseandETFUniverseSelectionModel(FundamentalUniverseSelectionModel):
def init(self, Period=1, filterFineData=False, universeSettings=None, universeCount=10):
super().init(filterFineData, universeSettings)
self.universeCount = universeCount
self.stateData = {}
self.spy_constituents = []

def SelectCoarse(self, algorithm, coarse):
    # Retrieve SPY constituents
    self.Universe.ETF("SPY", Market.USA, self.UniverseSettings, spy_constituents)
    # Only analyze equities that are constituents of the SPY ETF
    spy_constituents = lambda constituents: [x.Symbol for x in constituents]

    for c in spy_constituents:
        if c.Symbol not in self.stateData:
            self.stateData[c.Symbol] = self.SelectionData(c.Symbol, 1)

        avg = self.stateData[c.Symbol]
        avg.update(c.EndTime, c.Price, c.Volume)

    values = [x for x in self.stateData.values() if x.volume > 100000.............
What am I doing wrong? Could you provide a Python example or missing docs please?`

**Comment by jaredbroad** [comment]
https://www.quantconnect.com/docs/v2/writing-algorithms/universes/chained-universes
