### ISSUE TITLE
Incorrect Deployment Target names

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#957]
#### Expected Behavior

On [Deployment Targets](https://www.quantconnect.com/docs/v2/local-platform/key-concepts/deployment-targets), the deployment target names match the names we see in VS Code.

#### Actual Behavior

The names are different.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Closed by https://github.com/QuantConnect/Documentation/pull/1054
