### ISSUE TITLE
C# libraries in Environments

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#971]
#### Expected Behavior

The non-default H3's [here](https://www.quantconnect.com/docs/v2/writing-algorithms/key-concepts/libraries) and [here](https://www.quantconnect.com/docs/v2/cloud-platform/projects/package-environments) only show the Python libraries, since the environment feature is only for Python projects. 
- Remove C# button from the non-default H3

#### Actual Behavior

The H3's show C# and Python libraries for each environment.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/pull/1056
