### ISSUE TITLE
Tick History Requests

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#977]
#### Expected Behavior

The tick history request docs in Writing Algorithms and Research Environment explain the various ways to request historical tick data
- `History(symbol, start, end, resolution)` => DataFrame of Quote ticks
- `History(type, symbol, start, end, resolution)` => DataFrame of Quote + Trade ticks
- `History[Tick](symbol, start, end, resolution)` => Just last tick of each slice

#### Actual Behavior

This information isn't documented. Waiting on fix in response to https://github.com/QuantConnect/Lean/issues/4297#issuecomment-1246005199

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Awaiting https://github.com/QuantConnect/Lean/issues/4297#issuecomment-1246005199 fix
