### ISSUE TITLE
ObjectStore limits image is out of date

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#978]
#### Expected Behavior

The image in [Edit Storage Plan](https://www.quantconnect.com/docs/v2/cloud-platform/data-storage#07-Edit-Storage-Plan) shows the correct storage limit options.

#### Actual Behavior

The image is outdated.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
Closed by https://github.com/QuantConnect/Documentation/pull/1055
